### ISSUE TITLE
Telegram bot bugs + improvements

### ISSUE THREAD

**Issue by mochet** [Joystream/community-repo#10]
Now that the bot is live, it will hopefully be easier for people to propose/improve upon it. We could hopefully create small bounties for these.

- The proposal notification Title field is actually taking from description/rationale. There is a title field and it should be what is shown.
- When announcing a new election cycle or stage, it would be nice for the bot to include a rough indication in human readable format of the time this stage will be active for. (ex. "This phase lasts for ~24h")
- A reminder notification for highly important events, like election announce period would be great. The current announce period is 24h, so after the initial bot notification a reminder could be made at 16h to ensure people in different time zones are aware.

**Comment by mochet** [comment]
More issues/improvements:
- New thread creates 2x announcements, one for the new thread and one for the 1st post. This is redundant and causes spam on Telegram.
- It seems there is a rare bug where a post/thread might be displayed twice, the screenshot below shows that the post IDs were different, but only one of them actually exists:
![image](https://user-images.githubusercontent.com/50830161/90334621-0a7f3a80-dfe0-11ea-9bfa-7fa8a041e393.png)

**Comment by mochet** [comment]
Suggested by @bedeho :
- Add a list of members correlated with their Telegram handles. When reminder notifications are made for proposals, the bot can tag specific users who have not voted yet for proposals.

Ideally the list would just be a text file or something very easy to modify.

**Comment by mochet** [comment]
A missing feature is that comments left on proposals are not announced by the Telegram bot. This would be a nice feature to have as otherwise people are not aware of comments being made in this area of the platform, unlike the forum section it does not have a recent activity list.

**Comment by bitoven-dev** [comment]
Yes, there are many improvements that can be made. I actually only try to meet the KPI requirements at first. So it is on the minimal feature.
Also I want to know, what are the steps for further improvement of the bot (or maybe all of the existing community repo)? 
Do we need to create proposal again or we can just directly make pull request for it?

**Comment by mochet** [comment]
> Also I want to know, what are the steps for further improvement of the bot (or maybe all of the existing community repo)?
> Do we need to create proposal again or we can just directly make pull request for it?

This was discussed in the initial improvement of the community repo: https://github.com/Joystream/community-repo
`It is likely in the future we will have to accomodate revisions and improvements of previous submissions. This process will be refined when this becomes a necessary task.`

So there is no actual process for this yet. I think for minor changes it really shouldn't require a proposal, but for major improvements/changes, especially those asking for funding, there should be a proposal made. I'll create a forum thread to discuss this.

**Comment by mochet** [comment]
Another feature that would be nice to have is some scripts be able to return a value, for instance the HELIOS script which returns information about current storage providers, could be accessed by someone typing !HELIOS in chat (or whatever method works for triggering the script to run and return its value).

**Comment by mochet** [comment]
The Kusama network has an interesting bot that periodically posts network stats, it can also be refreshed:
![image](https://user-images.githubusercontent.com/50830161/91706908-1b0ee380-eb90-11ea-81f8-ff08f89eaf1e.png)

**Comment by bitoven-dev** [comment]
Now, the forum has more activities, the double bug is surely become annoying. Especially on double proposal bug that was breaking/stopping the bot 
I think I just have an idea to solve the double bug on telegram bot, that is by parsing new event with `api.query.system.events` and only then it will notify the telegram. 
Currently what the bot doing is querying `forum.nextPostId` and then calculate the current post id. And compare for any change on  `forum.nextPostId`
This fix, I believe is also more efficient and consuming less resource 
But it will more or less rewrite most of the code. 😅 
I just want to make sure that all of events can be found on https://testnet.joystream.org/#/explorer (`api.query.system.events`), right @bwhm ?

**Comment by bwhm** [comment]
> Yes, there are many improvements that can be made. I actually only try to meet the KPI requirements at first. So it is on the minimal feature.
> Also I want to know, what are the steps for further improvement of the bot (or maybe all of the existing community repo)?
> Do we need to create proposal again or we can just directly make pull request for it?

When the new KPI system is out, improving the telegram bot will surely be included!

Before then, I don't think we'll have time to focus on it...

**Comment by bwhm** [comment]
> Now, the forum has more activities, the double bug is surely become annoying. Especially on double proposal bug that was breaking/stopping the bot
> I think I just have an idea to solve the double bug on telegram bot, that is by parsing new event with `api.query.system.events` and only then it will notify the telegram.
> Currently what the bot doing is querying `forum.nextPostId` and then calculate the current post id. And compare for any change on `forum.nextPostId`
> This fix, I believe is also more efficient and consuming less resource
> But it will more or less rewrite most of the code. 😅
> I just want to make sure that all of events can be found on https://testnet.joystream.org/#/explorer (`api.query.system.events`), right @bwhm ?

If you mean whether the explorer tab will display add **all** new events as they come in, then no. Click on a block, and you'll see there are more. It **should** show all non-trivial ones, but I haven't double checked that...

**Comment by mochet** [comment]
Since there is now a new bot, I will close this issue and we can move discussion to: https://github.com/Joystream/community-repo/issues/38
