### ISSUE TITLE
Community Bounty #12 - "Deploy Reliable Endpoints"

### ISSUE THREAD

**Issue by bwhm** [Joystream/community-repo#101]
### Tags
- `Coding`, `Marketing`

## Description
Our endpoint has come under a lot of stress with the large inflow of new users. Providing endpoints may become a "formal" role in future testnets`*`, but we think it could be an informal role in the near future.

`*` as pioneer will in the future connect to a query node, it will likely be part of the scope of the query node operators to also provide a websocket endpoint.

### Reward
USD 100 as a one time payment (for up to two members),
and the Council will be given a budget for biweekly recurring rewards that should cover the cost plus a negotiated fee.

### Resources
- The command `./joystream-node --help` will display plenty of configurable options for the node. Some of these "must" be updated to provide a good endpoint.
- Using a load balancer may be preferable to running one "big" node.
- Running the node(s) with docker may be better than systemd
- Note that our current endpoint is hosted by Linodes in Frankfurt, Germany so hosting with a different provider and from a different geographic location could be a benefit.

### Format
Jsgenesis prefers the Council comes up with a format, as there are benefits and downsides with both.

The Council will be responsible to set the full rules, and can choose two winners that will both get USD 100 in tJOY.

### Success Events
1. Deploy a public endpoint with high capacity - USD 100.

The endpoint must be deployed on sufficiently strong hardware, and the following information must be shared in full. Based on the initial information shared in the application, the Council will approve your spending proposal.

2. Ensure close 100% uptime, and relieve some of the pressure on the current endpoint.

The Council will be given a budget to provide compensation, depending on the approved proposals. Note that before the inflow, Jsgenesis spent approx. USD 120/month on endpoints (that cost has since gone up). Up to USD 200 per month (USD 100 per Council term) will be approved without question.

### Conditions
When a PR is made for Jsgenesis to review, the following information is required:
- Specs and location (hardware)
- Configs and flags (node)
- Endpoint URL (for testing)
- SSL

### Annihilation
- Any information provided is found to be incorrect
- Excessive logging/spying on users
- Any other "malicious" actions

### Review Period
- Up to 1 week after the PR is submitted

### Status
DRAFT

**Comment by mochet** [comment]
this bounty is now closed, there are already deployed endpoints that manage this task well.
