### ISSUE TITLE
Runtime upgrade proposal

### ISSUE THREAD

**Issue by bwhm** [Joystream/community-repo#105]
## Rationale
With the inflow of new users, there are lots of urgent matters that needs to be addressed.

This text proposal will only address those can, and need to be, solved by a runtime upgrade. In particular, it aims to allow more users to participate on the network, and improve capacities where needed.

### Validators
The perhaps easiest way to become an active participant on the Joystream network is to run a node. At the moment, there is also no good way for us to track the the uptime and reliability of a node operator without them being validators. Although this is something being worked on, the easiest and best solution (in a vacuum) is to lower the bar to become a validator.

#### Max Validators
Currently, the highest number of validators that can be proposed by a the Council is set to 100. There are some clear drawbacks in allowing "too many" validators, (increases the blocktime, reduces the rewards, etc.), but we beleive that the Community should be allowed to decide this. Polkadot currently "only" allows 297, so we are hesitant to allow much more than this without having tested it for a while.

We propose giving the Council the option to increase this number from 100 up to 300.

#### Rewards
Part of the equation around this are the rewards for the Validators and Nominators. We were initially also planning on increasing this, as they are arguably losing money on their operations as of now, but after giving it some thought, it's not clear that is the correct way to go:
- The Validators/Nominators already gets ~55% of the total platform inflation as rewards, while also staking ~55%.
- While they do have higher costs than some "official" roles, it requires very little time after initial setup.
- Increasing the rewards will mean that some "whales" will be able to operate a large number of nodes profitably, while Community Members wanting run one validator to earn points to become Founding Members will be pushed out due to their lower stakes.

For these reasons, we propose keeping the rewards as they are for the time being.

#### Slashing
On the previous network, slashes was very frequent, and the amounts were high. Most Validators ended up losing tokens, so we chose to increase the rewards and limit the risks of slashes. The latter was mostly a consequence of reducing the `unbonding` period from ~1 month to ~24h. This had both the benefit described abobe, and allowed users to more quickly allocate their resources to other voting and/or staking for other roles. Without going in to too many details, the `unbonding` period for Validator and Nominator stake is related to slashing, as there is no point in slashing someone if they are able to move their tokens **before** they get slashed.

We propose adjusting this up to ~7 days, so that Validators must be more careful, and make it less tempting for "whales" to risk and lock up their tokens for a longer period of time.

### Council
The size of the Council was adjusted in a recent proposal, and there will be 12 slots instead of 6 from the next term forward. Although we believe the effects of this should be monitored before increasing again, we propose changing the two hardcoded values for the `Set Election Parameters` proposal:
- Min Candidacy Limit from 25 to 50
- Max Council Size Limit from 20 to 30

These changes are rather small, but we believe it should be "enough" until the next testnet.
Note that, as with `Max Validators`, these changes does nothing by itself, but gives the Council the possibility to expand the Council more in the future.

### Proposals
The proposal system is seeing more and more use.

Currently, there is platform a limit on that only allows 5 *active* proposals at the time. This was meant to allow the Council more time to evaluate each proposal, and not get discouraged by always having to deal with "infinite" proposals.

#### Max Active Proposals
As long term Community Members have gotten more used to dealing with proposals, and the proposal system has found more and more use cases (rewarding creative users, managing bounties, etc.), we believe it's time to increase this number. We propose adjusting this to 10 or 12, but we would want your input on this.

#### Increase the Stakes
We still believe too many open proposals at all times will lead to lower "quality" proposals and voting. Another way to limit proposals is to change the price (eg. stake).

We propose changing the required stakes as follows:
- `Text`: 25k -> 50k
- `Runtime Upgrade`: 1M -> 5M
- `Set Election Parameters`: 200k -> 1M
- `Spending`: 25k -> 50k
- `Set Validator Count`: 100k -> 500k
- `Add Working Group Leader Opening`: 100k -> 200k
- `Set Working Group Mint Capacity`: 50k -> 200k
- `Begin Review Working Group Leader Application`: 25k -> 50k
- `Fill Working Group Leader Opening`: 50k -> 200k
- `Slash Working Group Leader Stake`: 50k -> 200k
- `Decrease Working Group Leader Stake`: 50k -> 200k
- `Set Working Group Leader Reward`: 50k -> 200k
- `Terminate Working Group Leader Role`: 100k -> 200k

We are not "sure" on many of these values, but a quick rationale:
- `Text` and `Spending` are the two most common ones, and also the most likely "needed" by newcomers. They will often require the least amount of time to evaluate, and `Spending` will sometimes be the only way for newcomers to earn tokens in the first place.
- All `*Working Group*` proposals are rarely used as is, and many are "blocked" in the first place, so no need for big adjustments
- The rest (`Runtime Upgrade`, `Set Election Parameters`, `Set Validator Count`) are arguably the most critical ones, and should not be taken lightly by the proposer or the Council. The runtime upgrade, which could destroy the chain, will also see a lower grace period (from 5 to 2 days) to allow us to always use the proposal predictably in the future, instead of using `sudo`.

**Comment by bwhm** [comment]
#### How to fix the current "mess" with validators
This issue is, in our opinion, a little complex, as there are factors pointing in different directions.

- Becoming a Validator is the "cheapest" way to actively join the network, and hence a great place for new users to participate.
- The Validators/Nominators may already be in the red and will clearly not be profitable with more validators (without increasing rewards).
- Increasing rewards (so they profit on the operation) will cement the current status, where "whales" can distribute tokens to ensure they can occupy lots of slots.
- There is no actual need for more Validators (arguable less), and they are already claiming more than 50% of the total inflation as rewards.
- Although chain security is a priority, the number of Validators (and stake) needed to secure a chain should be a function of it's value. Without presenting numbers, I'm fairly sure we are already far outside the realms of what is reasonable,  and they are already claiming more than 50% of the total inflation as rewards.
- Adding more nodes actually slows the network down, as it creates clusters of (Validator) nodes that are not connected to each other directly.

The "problem" is that the first point is, for our testnet, arguably the most important one. However, we have looked at the possibility of simply rewarding node-operators instead through our own [Joystream telemetry](https://telemetry.joystream.org/). This will hopefully be up and running within a couple of days...

This will make it less important to run Validator nodes as opposed to regular nodes, but it still doesn't change the fact that the current system (at least before the number of slots were increased from 40) ensures that "whales" gets an insurmountable token advantage, that can not be overcome. We don't want to increase reset the chain (and lose all history), and it's impractical to fix the current token distribution problem. Mainly because it would take time to allow all users to "cash out".

The solution proposed in the OP would primarily work as a band aid.

Another important consideration is that this would _not_ increase the number of slots, but simply give the Council the option to do so.

When it comes to unbonding/slashing, we agree that it's a bit of an issue that you can't vote with the tokens bonded for Validation. It's not _all_ bad, as it at least forces "whales" to choose one or the other (CM or Validate), but on balance it's probably bad. (We've discussed this quite a bit, and from the next major release (this summer most likely) this will be changed.

However, the current issue of slow blocks, and the extremely small risk of getting slashed (you basically have to do it on purpose), we think increasing to 1 week, or at least more than 24h, is worth it.

#### How to balance the need for opening proposals, with the cost of following up on them.

The proposal to both increase the number of slots, but simultaneously increase the cost of doing so, is primarily meant to ensure that there is "always" room for another proposal.

It is no doubt annoying for new users if they can't afford making proposals, but at the same time, we have to be conscious of the Council's time. Currently, they are doing a good job on most things, but managing Bounties has proven to be difficult. If some of the would be proposals was instead handled via forum/discord by a single CM or Bounty Admin/Manager, this seems  beneficial for all.

We were hesitant about increasing costs before making the proposal, and based on the feedback, it seems best not to go ahead with this for MOST proposals. Making "high risk" proposals (eg. Runtime Upgrade, Election Params and Set Validator Count) more expensive still seems reasonable. Feedback?

**Comment by freakstatic** [comment]
Good points! I agree there is indeed a problem of keeping increasing the rewards for validators since it's easier for a "whale" to keep getting more slots and in the end having control of most of the validators. 
About the increase of the cost of proposals I think would be better to only increase the ones you mention, text proposal and spending proposal should keep a low cost so that need users can also create them.

**Comment by mochet** [comment]
the runtime upgrade happened so this can be closed
