### ISSUE TITLE
FM launch questionnaire - KPI 12.4

### ISSUE THREAD

**Issue by bwhm** [Joystream/community-repo#113]
As stated in the KPI, the launch and first scoring period of the FM program is completed. The number of new community members has been (pleasantly) overwhelming, but it's clear that everything we've tried to communicate has not reached the entire community. It's also quite likely that there is lots of room for improvements in what was intended as well.

**Every member of the platform that has submitted  one or more summaries, *before* answering this questionnaire, will receive 5000tJOY!**
Ideally, the Council should make these payments frequently, and request a refund from Jsgenesis.

Some (further) notes for the Council:
1. Consider this a non-exhaustive list of question - the Council are free to add more!
2. Feel free to make it multiple choice where applicable
3. Jsgenesis must not receive or get access the "raw" data, we want to preserve the responders anonymity so they can answer "freely". 
4. The only "personal" data we want is the `memberId` and `account` of all responders.
5. Make sure the report gives a good overview of the responses, so that we know roughly how many answered in a similar way.

---

**New users only (and optional)**
1. How did you find us?
2. Where are you from?
3. Age bracket (18-24, 25-35, 36+)

**All users**
#### Submitting Summaries
1. Did you experience any *technical* issues submitting your summary?
2. What was the biggest challenge filling out your summary?
3. How many times have you submitted?
4. Did you know that you _should_ only submit at the end of each scoring period?
5. Did you know that you can submit your summary for scoring period 1 even after scoring period 3 is completed?

#### The Founding Members Program
1. Were you aware of the referral program?
2. Were you aware that the program is not over after the first scoring period?
3. Were you aware that it's not enough to participate on the first scoring period only?
4. Have you read the terms, rules and "procedures"  in the [Founding Member repo](https://github.com/Joystream/founding-members)?
5. What have you done to earn points thus far?
6. What are you planning on doing to earn points in the future?

#### Joystream
1. What do you think Jsgenesis (the company developing Joystream) will do after Joystream goes live on mainnet?
2. Are you aware that we have many open bounties, that pays in tJOY?
3. Did you know you can exchange your tJOY for Bitcoin Cash?

**Comment by lopegor** [comment]
Hi Everyone! I have produced a summary of the survey and sent a PR. Please, have a look: https://github.com/lopegor/community-repo/pull/1

**Comment by lopegor** [comment]
Hello Everyone! Here's the survey summary: https://github.com/Joystream/community-repo/pull/124

**Comment by bwhm** [comment]
All transfers completed!
blocks:
- [2,403,379](https://testnet.joystream.org/#/explorer/query/0xadd6697fcf8d11da589bc5cc24835edc35d8b054bbca2c8624a5b8900e721c6c)
- [2,403,380](https://testnet.joystream.org/#/explorer/query/0xc40769554c8f63510489df23ba61c1c42ee435219e89f35e2ad3b6a6864ae47c)
- [2,403,381](https://testnet.joystream.org/#/explorer/query/0xa737e5af59e8b03f7369738c4ce89a62b44eda067eb967277025f2486667ce49)

**Comment by Marek188** [comment]
https://testnet.joystream.org/#/members/flakes9776
I put # like a Discord name, can you please send me 5k Joy?

**Comment by lopegor** [comment]
@Marek188 , sent

**Comment by mochet** [comment]
this was completed so closing issue
