### ISSUE TITLE
Joystream Community Call

### ISSUE THREAD

**Issue by bedeho** [Joystream/community-repo#13]
# Joystream Community Call

## When

15:00pm UTC, 27th of August.

## Duration

60 minutes.

## How

We will use Zoom:

https://us02web.zoom.us/j/85258405364

## Recording

We will record, and we may end up publishing an edited version on Joystream and/or YouTube in the future.

## Privacy

If you are concerned about your privacy, just join with
your camera turned off, with a pseudonymous handle and if you also want to speak, you could use a distorter like [VoiceMod](https://www.youtube.com/watch?v=16Dg3S9AVZg).

## Host

The hosts will be the following from Jsgenesis

- Bedeho
- Martin
- Ben

## Structure

1. Introductions: everyone who wishes to give a brief introduction, please write your name in the chat, and you will get the mic.
2. Point of Discussion: What is the best way to share our progress & plans?
3. Questions&Answers + discussion.
4. (If time permits) Show and Tell: Preview of new video consumer experience on Figma.

## Questions&Answers

There were way too many questions for this one call, so we picked a few, then we can have some discussion based on those. Other questions will be addressed in later calls.

**Comment by mochet** [comment]
This community call was completed and the video was uploaded to Joystream, you can find it here: https://testnet.joystream.org/#/media/videos/939
