### ISSUE TITLE
Community Bounty #14 - "Compile List of Polkadot/Substrate Content"

### ISSUE THREAD

**Issue by bwhm** [Joystream/community-repo#142]
### Tags
- `Content`
- `Research`

### Description
In order to get more high quality content available on the platform, that also have some educational value, we want to source content about Substrate (the framework Joystream is built on) and Polkadot.

We know there are podcasts, and likely Youtube (etc.) channels, with an emphasis on the progress and development for Polkadot and Substrate, but also other projects in the ecosystem.

There should also be plenty of "standalone content", such as talks, interview, conferences demonstrations, developer presentations, etc. These are also welcome, but there will be higher requirements to the quality of content, as there will be more overhead to get permissions.

#### Reward
Up to $50 per channel, or $25 per podcast.
Up to $20 per video, and $10 per audio only content.

#### Success Events
1. For each unique channel/podcast, provide the following information:
  - URL
  - Name
  - Description
  - How many *relevant* videos/episodes exist
    - If the channel/podcast covers a wider range of topics, include URLs to the relevant videos/episodes
  - Date of last video/episode
  - License/copyright details
  - Contact information (for the creators/owners)
  - Twitter/Telegram/Fb or other social media accounts
2. For each standalone video/audio content, provide the following information:
  - URL
  - Name
  - Description
  - Length
  - Date of last video/episode
  - License/copyright details
  - Contact information (for the creators/owners)
  - Twitter/Telegram/Fb or other social media accounts

**Bonus**
If you are able to acquire the permission to publish the content, or get the creators to do so themselves, there may be a significant bonus to the reward(s).

#### Resources
NA

#### Conditions
Note that content that primarily targets traders does not qualify for rewards.

#### Annihilation
NA

**The below applies to the Bounty Manager/Council only, and is not necessarily relevant for the entrants.**

#### Format
Jsgenesis proposes and ["Open"](https://github.com/Joystream/helpdesk/tree/master/roles/council-members#open-format). However, the BM/Council are free to choose any format they see fit.

The results should be aggregated in to a single document, maintained by the Bounty Manager (BM) until the Bounty is closed/completed.
As there is little need for continuity, and the Bounty may stay open indefinitely, the Council may select a new BM at each new Term. (The "next" Council will decide this.)

As part of the BMs responsibility, the forum post associated with this Bounty must contain a list of (or link to) all submitted sources, to avoid community members duplicating each others work.

#### Review Period

Jsgenesis may take 10 days after the data has been included/updated in a PR to the Community Repo, with an approved spending proposal.

#### Status
**Open**

**Comment by mochet** [comment]
For anyone interested in this bounty, you should post all questions and work in this forum thread: https://testnet.joystream.org/#/forum/threads/358

**Comment by mochet** [comment]
This bounty has been discontinued, all entries recieved on the forums before the closing deadline will be graded + rewarded.
