### ISSUE TITLE
Community Bounty #15 - "Summary/Transcripts of Community Update Videos"

### ISSUE THREAD

**Issue by bwhm** [Joystream/community-repo#143]
### Tags
- `Content`
- `Research`

### Description
The first "season" of a video series of Joystream Community Updates, containing 7 episodes has been published under [this channel](https://play.joystream.org/channel/XXXXX) (and on [Youtube](https://www.youtube.com/channel/UCFMd2TpYSChOaVJPX84YUmA)).

In order to reach a wider audience, we want the community to translate the videos to other languages (See bounty #16). To make this easier, we first want a good summary of what is being said in English.

As we plan to introduce subtitles for the video, we also want to produce these. Although subtitles should be based on an actual transcript rather than a summary, the work is similar enough to combine in to one bounty.

It is assumed that youtube transcriptions can serve as a good starting point, but will need re-writing.

#### Reward
$250 for a good summary of the presentations
$100 extra for a complete set of transcriptions for the series
$100 extra for good English subtitle tracks

The Council may also distribute rewards of up to $50 to entrants that submitted a high quality efforts, but was bested by one or more entrant.

#### Success Events
1. Submit a summary of each presentation in `.md` format.
  - The summary should "clean" up the language, but stay true to the message that is being conveyed and include all information provided
  - For each slide in every video:
    - `videoId`, `slideId`, `timestamp_start`:
    - "Block of text"
2. Submit a complete transcript of all videos in `.md` format.
3. Submit subtitle tracks for all videos in `.srt` format.
  - As 2. and 3. should be performed simultaneously, it's advisable to write in the `.srt` standard, then simply edit out superfluous information.

#### Resources
- The slides used in the original can be found in [PDF](https://github.com/Joystream/community-repo/files/6330921/Joystream_Community_Update_1.pdf) (low res) and [jpeg format](https://github.com/Joystream/community-repo/files/6330929/Joystream_Community_Update_1_jpeg.zip) (high res).
- The youtube auto-generated transcripts are available for each video [here](https://www.youtube.com/channel/UCFMd2TpYSChOaVJPX84YUmA).
- Example of formatting for `.srt` can be found [here](https://en.wikipedia.org/wiki/SubRip)

#### Conditions
- The transcript should follow basic transcription standards
- If any instructions are needed for the subtitles to work, these must be included
- All work must be licensed [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)

#### Annihilation
- The summary or transcripts contains considerable changes of the original script

**The below applies to the Bounty Manager/Council only, and is not necessarily relevant for the entrants.**

#### Format
The Council and/or BM is free to choose format, but as Success Event 1 is needed to start Bounty #16, it would be good to organize in such a way that:
- It could be completed (or a good draft presented) as soon as possible
- Success Events 2 and 3 could be a separate milestone

This could be addressed by having Success Event 1 "open", and assigning the winner to Success Events 2 and 3.

Finally, the BM may choose to split the rewards between more than one entrant, if the final result end up being a combination of their works.

#### Review Period
Jsgenesis will perform a review of Success Event 1 within 3 days of the PR being marked ready for review. Subsequent reviews may take up to 14 days.

#### Status
**Open**

**Comment by mochet** [comment]
For anyone submitting work for this bounty, you should direct all questions to the forums on this thread: https://testnet.joystream.org/#/forum/threads/363

**Comment by mochet** [comment]
A user has submitted all of the work in the following PR: https://github.com/Joystream/community-repo/pull/199

It has to be graded still.

**Comment by mochet** [comment]
This bounty was completed.
