### ISSUE TITLE
Community Bounty #16 - "Translation of Community Update Videos"

### ISSUE THREAD

**Issue by bwhm** [Joystream/community-repo#144]
### Tags
- `content`
- `documentation`

### Description
The first "season" of a video series of Joystream Community Updates, containing 7 episodes has been published under [this channel](https://play.joystream.org/channel/ABDC) (and on [Youtube](https://www.youtube.com/channel/UCFMd2TpYSChOaVJPX84YUmA)).

In order to reach a wider audience, we want to have them translated to a variety of languages in order to reach more people in locations where english is not as widely spoken.

To avoid spending significant time transcribing the original content for translation, see the full transcripts [here](https://github.com/Joystream/community-repo/TBD).

#### Reward
- $250 for a high quality recording of the entire series
- $50 extra for transcriptions (in the same language)
- $100 extra for subtitle tracks in `.srt` format

The Council may also distribute rewards (up to $50 per language) to entrants that submitted a high quality effort for "Introduction", but was not bested by one or more entrant.

#### Success Events
1. Record the "Introduction" in a language where you are at least [IRL Level 4](https://en.wikipedia.org/wiki/ILR_scale#ILR_Level_4_%E2%80%93_Full_professional_proficiency).
2. If `assigned` by the Bounty Manager (BM), record the remaining 6 episodes in the same "style" as the introduction.
3. Submit a complete transcript of all videos in `.md` format.
4. Submit subtitle tracks for all videos in `.srt` format.
  - As 3. and 4. should be performed simultaneously, it's advisable to write in the `.srt` standard, then simply edit out superfluous information.

#### Resources
- The slides used in the original can be found in PDF (low res) and PNG format (high res) [here](https://github.com/Joystream/community-repo/tree/master/documentation/bounty15).
- The English transcripts can be found [here](https://github.com/Joystream/community-repo/tree/master/documentation/bounty15).

#### Conditions
- The video deliverable should be either:
  1. "Just" a new audio track over the original videos
  2. Still images from the original videos with
  3. A complete remake using the PNG images
- The recording must at least be HD quality
- Audio quality must be at least as good as the original (we're considering re-recording them, and any new series will certainly be higher quality)
  - Computer microphone, and regular headsets is _very_ unlikely to be approved
- Your work must be licensed [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)

#### Annihilation
- The video contains any personal "plugs" (such as affiliate links, etc.)
- The translations contains considerable changes of the original script
- Any violation of copyrights of any kind

**The below applies to the Bounty Manager/Council only, and is not necessarily relevant for the entrants.**

Note that there should be separate BMs for each language. Where possible, the BM should be at least proficient in both English and the language it's being translated to. If required, they can instead find some trusted source to verify.

#### Format
For what the BM considers "popular" languages:
- Jsgenesis proposes an open format for the "success event" 1 - allowing anyone to submit their recording within some pre-defined time frame.
- After a review period, the best candidate for each language is `assigned`, and given some time to either complete the series, or for each milestone (eg. `n/m` videos).

For what the BM considers less "popular" languages:
- If an entrant shows an interest in a particular language, the BM can choose how to proceed.
- It seems prudent to at least ask for some samples before they are `assigned` the whole series.

All videos in a single language must follow the same "style" (ref. conditions), but individual BMs may choose to require one or another "style".

#### Review Period
Depending on the language, Jsgenesis grading can take some time. In most cases, 10 days should be sufficient.

#### Misc
Initially, we are targeting the languages listed below only, but the Council may choose to approve other languages`*` if they see fit.
- Russian
- Spanish
- French
- Portuguese
- Arabic (Modern Standard Arabic)
- Chinese (both Cantonese and Mandarin)
- Japanese
- Korean

`*` This list is based solely on our estimates and guesses about our current community, and what we consider "more likely" future Community members. This leaves out large "markets" - especially in Asia. Serious applicants for other languages should be considered.

It is assumed translating the written content of the presentation itself is not required. However, the BM can choose to overrule.

#### Status
**Open**
Note that some changes should be expected for the transcripts, as mentioned [here](https://github.com/Joystream/community-repo/pull/199).

**Comment by lopegor** [comment]
Hi! Links to slides and transcripts are broken.

**Comment by bwhm** [comment]
Hey @lopegor 
This bounty "needs" #15 first...
Will upload the slides though!

**Comment by bwhm** [comment]
@mochet @maxlevush 
Please review! I'll make a PR with slides now.

**Comment by maxlevush** [comment]
Hi!
Sounds good. I think we can release it. 
Will see how many languages the community will take

**Comment by maxlevush** [comment]
Open https://testnet.joystream.org/#/forum/threads/510

**Comment by giada42** [comment]
@bwhm The Joystream channel link is broken.

**Comment by rustamkakar** [comment]
Hi!
Recorded Russian translation with original video and unique audio recorded by me. 
https://youtu.be/2Mn02ADsSQ0
Please check. Thanks

**Comment by maxlevush** [comment]
@rustamkakar Hey. 
You don't need to report here. 
Do it here https://testnet.joystream.org/#/forum/threads/510

**Comment by rustamkakar** [comment]
Hey! It’s already there
:)
вт, 27 июля 2021 г. в 09:00, maxlevush ***@***.***>:

**Comment by mochet** [comment]
This bounty is no longer relevant to the new system, closing this to avoid confusion
