### ISSUE TITLE
Community Bounty #17 - Discord Video Bot

### ISSUE THREAD

**Issue by mochet** [Joystream/community-repo#151]
### Tags
* `Coding'

A bot that monitors all uploads of videos on the platform and posts them in a dedicated Discord channel.
This will help with:
- people being made aware of new uploads
- people being able to rate videos on Discord

The bot should include some information about the video:
- Channel
- Username
- Video Duration
- Categories / Tags
- Language

**Comment by mochet** [comment]
This is now a bounty with a $100 reward via approved text proposal: https://testnet.joystream.org/#/proposals/17

**Comment by bwhm** [comment]
FYI,
With `sumer` - to be released in three weeks/soon (TM), this would not work anymore :(

**Comment by mochet** [comment]
> FYI,
> With `sumer` - to be released in three weeks/soon (TM), this would not work anymore :(

thanks, have informed people that it is paused until the new release!

**Comment by mochet** [comment]
This bounty has now been assigned: https://testnet.joystream.org/#/proposals/138

**Comment by singulart** [comment]
https://github.com/Joystream/community-repo/pull/196

**Comment by mochet** [comment]
This bounty was completed.
