### ISSUE TITLE
KPI 1.6 - PRs/Issues that require Jsgenesis action

### ISSUE THREAD

**Issue by mochet** [Joystream/community-repo#159]
KPI link: https://blog.joystream.org/antioch-kpis/#1.6

Notes:
* I left out some issues which were just ideas since there isn't really any action to take for these for the time being.
* I left out several issues which were just starting points in the community repo and don't require any response.

| #  | repo           | PR link                                               | Classification                | Action Required                       |
|----|----------------|-------------------------------------------------------|-------------------------------|---------------------------------------|
| 1  | Joystream      | https://github.com/Joystream/joystream/issues/2351    | Bug Report (pioneer)          | unknown (pioneer v1)                  |
| 2  | Joystream      | https://github.com/Joystream/joystream/issues/2264    | Bug Report (pioneer)          | unknown (pioneer v1)                  |
| 3  | Joystream      | https://github.com/Joystream/joystream/issues/2213    | Improvements (CLI)            |                                       |
| 4  | Joystream      | https://github.com/Joystream/joystream/issues/2192    | Improvements (Forum)          | unknown (pioneer v1)                  |
| 5  | Joystream      | https://github.com/Joystream/joystream/issues/2177    | Wishlist (Proposals)          |                                       |
| 6  | Joystream      | https://github.com/Joystream/joystream/issues/2146    | Improvements (CLI)            |                                       |
| 7  | Joystream      | https://github.com/Joystream/joystream/issues/1958    | Improvements (Proposals)      |                                       |
| 8  | Joystream      | https://github.com/Joystream/joystream/issues/1653    | Bug Report (pioneer)          | unknown (pioneer v1)                  |
| 9  | Joystream      | https://github.com/Joystream/joystream/issues/1464    | Bug Report (forums)           | unknown (pioneer v1)                  |
| 10 | Joystream      | https://github.com/Joystream/joystream/issues/1465    | Bug Report (chain state)      |                                       |
| 11 | Joystream      | https://github.com/Joystream/joystream/issues/1457    | Improvements (Pioneer)        | unknown (pioneer v1)                  |
| 12 | Joystream      | https://github.com/Joystream/joystream/issues/1424    | Polkadot-JS integration       | unknown (pioneer v1)                  |
| 13 | helpdesk       | https://github.com/Joystream/helpdesk/issues/52       | Outdated Documentation fix    | Can be closed (outdated)              |
| 14 | helpdesk       | https://github.com/Joystream/helpdesk/issues/26       | Outdated Documentation fix    | Can be closed (outdated)              |
| 15 | helpdesk       | https://github.com/Joystream/helpdesk/issues/81       | query                         | Needs to be answered (maybe outdated) |
| 16 | helpdesk       | https://github.com/Joystream/helpdesk/issues/82       | query                         | Can be closed (outdated)              |
| 17 | helpdesk       | https://github.com/Joystream/helpdesk/pull/92         | correction                    | Unnecessary change                    |
| 18 | community-repo | https://github.com/Joystream/community-repo/pull/96   | bounty/competition            | can be merged                         |
| 19 | community-repo | https://github.com/Joystream/community-repo/pull/141  | update types                  | can be merged                         |
| 20 | community-repo | https://github.com/Joystream/community-repo/pull/145  | update script                 | can be merged                         |
| 21 | community-repo | https://github.com/Joystream/community-repo/pull/131  | bounty 13                     | can be merged                         |
| 22 | community-repo | https://github.com/Joystream/community-repo/pull/133  | bounty 13                     | can be merged                         |
| 23 | community-repo | https://github.com/Joystream/community-repo/pull/128  | bounty                        | can be merged                         |
| 24 | community-repo | https://github.com/Joystream/community-repo/pull/125  | document                      | can be merged                         |
| 25 | community-repo | https://github.com/Joystream/community-repo/pull/122  | bounty report                 | can be merged                         |
| 26 | community-repo | https://github.com/Joystream/community-repo/pull/108  | tokenomics generator update   | can be merged                         |
| 27 | community-repo | https://github.com/Joystream/community-repo/pull/103  | faucet bot                    | can be merged (?)                     |
| 28 | joystream-org  | https://github.com/Joystream/joystream-org/issues/249 | bug report                    | needs fixing                          |
| 29 | joystream-org  | https://github.com/Joystream/joystream-org/issues/222 | bug report                    | unknown                               |
| 30 | joystream-org  | https://github.com/Joystream/joystream-org/issues/220 | bug report                    | unknown                               |
| 31 | joystream-org  | https://github.com/Joystream/joystream-org/issues/47  | outdated website update issue | can probably be closed (?)            |
| 32 | joystream      | https://github.com/Joystream/joystream/pull/2191      | RU translation                | "checks were not successful"          |
| 33 | community-repo | https://github.com/Joystream/community-repo/pull/156  | council report                | can be merged                         |
| 34 | community-repo | https://github.com/Joystream/community-repo/pull/153  | tokenomics report             | can be merged                         |

**Comment by bwhm** [comment]
Addressed all the helpdesk ones, will proceed with the rest ASAP :)
