### ISSUE TITLE
Community Bounty #19 - "Validator Logging Tool"

### ISSUE THREAD

**Issue by bwhm** [Joystream/community-repo#161]
### Tags
`technical`

### Description
For the Founding Member program, a large part of the community is running validators nodes. With this, they are required to report the `eras` in which they are active.

To avoid everyone having to look through [this](https://github.com/Joystream/founding-members/blob/main/data/validators.js) file, which has also proven difficult for us to maintain, we want to make this data easily accessible on a server.

#### Reward
$400

#### Success Events
1. Create a tool that gets the `validator` set for each `era` - must also work for eras that are older than the `historyDepth` (meaning it must be able to read `.at` some older `blockHash`). It must get the following data:
  - era start/end, meaning the `blockHeight` and `timestamp`
  - total and individual `eraPoints` for said `era`
  - total and individual `stake` for said `era`
  - total and individual `nominators` for said `era`
  - the commission set by each `validator` for said `era`
  - total rewards for said `era`
  and store it in a db.
2. Create a primitive UI, that can be deployed on some server, that lets a user either select, or paste in/search for, their `stash` key, set a range of eras (with `blockHeight` and `timestamp` as helpers) and get:
  - a list of all eras (in range) of which the `stash` was a validator
  - the `eraPoints` earned for each, with "implied blocks" found (20 `eraPoints` = 1 block)
  - their `stake` in each `era` (distinguish between `own` and their `nominators`)
  - an estimate of their rewards for each `era` (again, keeping in mind `nominators`)

#### Resources
- The [status server](https://github.com/Joystream/status-endpoint-joystream/tree/development) is a good place to start for getting and storing the data.
- The [community repo](https://github.com/Joystream/community-repo/pull/141) contains some examples on how to get historical state
- Pioneer (with "Fully featured" enabled in settings) will provide an easy way to play around with the api using the "Chain state" tab. Almost all the state you need will be in the `staking` module.
- You can also use the "Javascript" tab for quick testing, without having to be concerned with types.

#### Conditions
- Code must be written in typescript, and compile to javascript
- All steps required to deploy and test the software must be documented step by step
- The PR must include a link to a demo for quick review
- All source code must be licensed as `GPLv3`
- Although there are no design requirements for the UI, it must be easy to understand and use

#### Annihilation
- Anything malicious hidden in the source code

**The below applies to the Bounty Manager (BM)/Council only, and is not necessarily relevant for the entrants.**

#### Format
The BM/Council is free to choose.

#### Review Period
Jsgenesis may take 10 days after the data has been included in a PR to the Community Repo, with an approved spending proposal.

#### Status
**Open**
~~Will be opened at block #277200 (New Council). May be edited/updated before then.~~

**Comment by mochet** [comment]
@bwhm can you please rename the title to bounty number 19

**Comment by bwhm** [comment]
Done!

**Comment by bwhm** [comment]
> @bwhm can you please rename the title to bounty number 19

@mochet 
please update the bounty json to include this!

**Comment by mochet** [comment]
To apply for this bounty please use the following forum link: https://testnet.joystream.org/#/forum/threads/381

**Comment by singulart** [comment]
Bounty task has been completed and is available for code review

Backend: https://github.com/Joystream/community-repo/pull/242
Front-end: https://github.com/Joystream/community-repo/pull/238

**Comment by mochet** [comment]
this bounty has been completed
