### ISSUE TITLE
Community Bounty #18 - "Original Video Content"

### ISSUE THREAD

**Issue by bwhm** [Joystream/community-repo#162]
### Tags
- `content`

### Description
As `The video platform DAO`, how to properly reward quality content creation on the protocol level is something we haven't developed yet. However, before we get there, we can reward it on a "social" level.

There is already a bounty in place for content in the [Public Domain](https://github.com/Joystream/community-repo/issues/88), but although you can technically license your original content as such, that bounty is looking for something different.

This bounty will aim to reward original content created by the user uploading it!

#### Reward
**Up to** $200 for high quality videos.
This is the maximum amount the Bounty Manager (BM) can recommend for a single video. However, the BM can ask Jsgenesis to increase the amount if they think the video warrants a higher reward.

(Note that in most cases, a smaller amount should be expected.)

#### Success Events
1. Produce a high-quality video:
  - Good resolution
  - Quality audio
  - Fun/interesting to watch
2. Upload it to the platform:
  - Good, and appropriate, metadata eg.
    - Thumbnail "matching" the video
    - Descriptive description :)
    - Appropriate category
3. Post your video for review by the Bounty Manager (BM) in the bounties forum thread (TBD).

---
If the producer wants to do a more "ambitious" project, this bounty can also be used to create a "promotional" video, explaining their project and further funding.

#### Conditions
The video is not required to be exclusive to the Joystream platform, but posting a video you have already published on another platform (e.g. YouTube) will significantly reduce the reward.

#### Annihilation
- the video violates **any** license or copyrights (and does not fall under "fair use")
- the video does not adhere to our ToS

**The below applies to the Bounty Manager/Council only, and is not necessarily relevant for the entrants.**

#### Format
Jsgenesis proposes an open format.

- The BM gets an initial budget for $500 per week.
- If they need an increase ($500 more), this must be approved by the Council.
- Further increases must be approved by Jsgenesis

- The BM (which *can* rotate for each Council), creates a forum thread for the bounty, where users can post links their videos.
- The BM ensures that the Curator team has approved the video
- The BM grades the video (and proposes a reward)
- Every week, the BM creates a list of new videos that qualify for a reward, then:
  - creates a (draft) PR to the [Community Repo](Jsgenesis proposes an open format) with their list
  - creates a spending proposal for the Council, linking to the PR above, with the reward destination being that of the Council Secretary
  - if approved, the Council secretary makes the individual payments, and marks the PR ready for review
- Jsgenesis merges the PR, and increases the Fiat pool

#### Review Period
Jsgenesis will review the PR (and increase the Fiat pool), within 7 days of it being marked ready for review.

#### Misc
If the BM is unsure how to grade a video, they should reach out to the other CMs (and potentially Jsgenesis) for advice (and guidance).

#### Status
**Open**
~~Will be opened at block #277200 (New Council). May be edited/updated before then.~~

**Comment by mochet** [comment]
This bounty has been opened and the way to submit is via this thread on the forums: https://testnet.joystream.org/#/forum/threads/422?replyIdx=1

**Comment by leetjoy** [comment]
Hello. I am leet_joy the Bounty manager for this bounty. 
How the rates are made: 
- I interview 3 others current content curators for their review and reward
- I made excel file and count average reward using formula 
X=(A+B+C+D)/4
where is: X - reward in USD A - leet_joy score B - Igrex score C - prontera score D - Meskalin score

Uploading here the list of total rewards.
[bounty18.xlsx](https://github.com/Joystream/community-repo/files/6629919/bounty18.xlsx)

Rewards:
Submission: https://testnet.joystream.org/#/forum/threads/422?replyIdx=2 -- 15USD
Submission: https://testnet.joystream.org/#/forum/threads/422?replyIdx=3 -- 77,5 USD
Submission: https://testnet.joystream.org/#/forum/threads/422?replyIdx=4 -- 12,5 USD
Submission: https://testnet.joystream.org/#/forum/threads/422?replyIdx=5 -- 2,875 USD
Submission: https://testnet.joystream.org/#/forum/threads/422?replyIdx=6 -- 7 USD/35 USD/11.25 USD

More detailed computation is in attached excel file.

**Comment by ZAZIK3** [comment]
[B18(12.08.2021).md.txt](https://github.com/Joystream/community-repo/files/6974121/B18.12.08.2021.md.txt)
Hello . I'm ZAZIK the Bounty manager for this bounty . Dates : start 10.08.2021 . How the rates are made:
I guide 2 other current content curators for thier review and reward . I made excel file and count average reward using formula avarage X=(A+B+C)/3 where is X- reward in USD . A - ZAZIK , B - marat_mu , C - arseniy2706 score.
Also we got helping from Igrex , he cheched my video with other curators and test 2 videos on working.
Rewards Submission : https://testnet.joystream.org/#/forum/threads/422?page=4&replyIdx=34 = 2,6
Rewards Submission : https://testnet.joystream.org/#/forum/threads/422?page=4&replyIdx=35 = 0 ( not playing )
Rewards Submission : https://testnet.joystream.org/#/forum/threads/422?page=4&replyIdx=36 = 2,6
Rewards Submission : https://testnet.joystream.org/#/forum/threads/422?page=4&replyIdx=37 = 15,3
Rewards Submission : https://testnet.joystream.org/#/forum/threads/422?page=4&replyIdx=38 = 1,6 
Rewards Submission : https://testnet.joystream.org/#/forum/threads/422?page=4&replyIdx=39 = 6 
Rewards Submission : https://testnet.joystream.org/#/forum/threads/422?page=4&replyIdx=40 = 35,6
Rewards Submission : https://testnet.joystream.org/#/forum/threads/422?page=5&replyIdx=41 = 5
Rewards Submission : https://testnet.joystream.org/#/forum/threads/422?page=5&replyIdx=42 = 19,1
Rewards Submission : https://testnet.joystream.org/#/forum/threads/422?page=5&replyIdx=43 = 6,6
Rewards Submission : https://testnet.joystream.org/#/forum/threads/422?page=5&replyIdx=44 = 3,3
Rewards Submission : https://testnet.joystream.org/#/forum/threads/422?page=5&replyIdx=45 = 5,6
Rewards Submission : https://testnet.joystream.org/#/forum/threads/422?page=5&replyIdx=46 = 0 ( not playing)
Rewards Submission : https://testnet.joystream.org/#/forum/threads/422?page=5&replyIdx=47 - 25 
Rewards Submission : https://testnet.joystream.org/#/forum/threads/422?page=5&replyIdx=48 - 9
Rewards Submission : https://testnet.joystream.org/#/forum/threads/422?page=5&replyIdx=49 - 14
Rewards Submission : https://testnet.joystream.org/#/forum/threads/422?page=5&replyIdx=50 = 1,6
Rewards Submission : https://testnet.joystream.org/#/forum/threads/422?page=6&replyIdx=51 = 5 ,6

**Comment by ZAZIK3** [comment]
> [B18(12.08.2021).md.txt](https://github.com/Joystream/community-repo/files/6974121/B18.12.08.2021.md.txt)
[table.xlsx](https://github.com/Joystream/community-repo/files/6985051/table.xlsx)
> Hello . I'm ZAZIK the Bounty manager for this bounty . Dates : start 10.08.2021 . How the rates are made:
> I guide 2 other current content curators for thier review and reward . I made excel file and count average reward using formula avarage X=(A+B+C)/3 where is X- reward in USD . A - ZAZIK , B - marat_mu , C - arseniy2706 score.
> Also we got helping from Igrex , he cheched my video with other curators and test 2 videos on working.
> Rewards Submission : https://testnet.joystream.org/#/forum/threads/422?page=4&replyIdx=34 = 2,6
> Rewards Submission : https://testnet.joystream.org/#/forum/threads/422?page=4&replyIdx=35 = 0 ( not playing )
> Rewards Submission : https://testnet.joystream.org/#/forum/threads/422?page=4&replyIdx=36 = 2,6
> Rewards Submission : https://testnet.joystream.org/#/forum/threads/422?page=4&replyIdx=37 = 15,3
> Rewards Submission : https://testnet.joystream.org/#/forum/threads/422?page=4&replyIdx=38 = 1,6
> Rewards Submission : https://testnet.joystream.org/#/forum/threads/422?page=4&replyIdx=39 = 6
> Rewards Submission : https://testnet.joystream.org/#/forum/threads/422?page=4&replyIdx=40 = 35,6
> Rewards Submission : https://testnet.joystream.org/#/forum/threads/422?page=5&replyIdx=41 = 5
> Rewards Submission : https://testnet.joystream.org/#/forum/threads/422?page=5&replyIdx=42 = 19,1
> Rewards Submission : https://testnet.joystream.org/#/forum/threads/422?page=5&replyIdx=43 = 6,6
> Rewards Submission : https://testnet.joystream.org/#/forum/threads/422?page=5&replyIdx=44 = 3,3
> Rewards Submission : https://testnet.joystream.org/#/forum/threads/422?page=5&replyIdx=45 = 5,6
> Rewards Submission : https://testnet.joystream.org/#/forum/threads/422?page=5&replyIdx=46 = 0 ( not playing)
> Rewards Submission : https://testnet.joystream.org/#/forum/threads/422?page=5&replyIdx=47 - 25
> Rewards Submission : https://testnet.joystream.org/#/forum/threads/422?page=5&replyIdx=48 - 9
> Rewards Submission : https://testnet.joystream.org/#/forum/threads/422?page=5&replyIdx=49 - 14
> Rewards Submission : https://testnet.joystream.org/#/forum/threads/422?page=5&replyIdx=50 = 1,6
> Rewards Submission : https://testnet.joystream.org/#/forum/threads/422?page=6&replyIdx=51 = 5 ,6
