### ISSUE TITLE
Bounty Idea - Founding Members Bot

### ISSUE THREAD

**Issue by mochet** [Joystream/community-repo#164]
This idea was suggested by oskarte on the forums as part of KPI 13.6.5: https://testnet.joystream.org/#/forum/threads/338?replyIdx=2

This just needs to have the JSON file containing the FM data: https://github.com/Joystream/founding-members/blob/main/data/fm-info.json

Some commands:
!lookup `username` : return the score of the user
!leaderboard : return the top 10 users on the leaderboard
!inducted : return the last 5-10 newly inducted members
!deadline : When is the deadline (HH:MM - DD:MM:YYYY) and how long until the deadline ("you have `n` until the scoring period is over
!status : What the current scoring period is, how many inducted founding members there are, how many points in total, average points

**Comment by traumschule** [comment]
PR: #237

**Comment by mochet** [comment]
this was completed
