### ISSUE TITLE
Documentation Improvements

### ISSUE THREAD

**Issue by spatsochi** [Joystream/community-repo#177]
#implemented-proposals
Overview
When the Council was first introduced, it was only able to vote on whether or not a runtime upgrade should be implemented. This rarely occurred, making the Council a rather insignificant part of the platform.
As the Council is meant to be **be** the executive arm of the Joystream governance system, we are adding a proposal system that will allow the users to control most of the day to day decision making on the platform.
#helpdesk
Description
Over time, the tasks should allow people with different **skillsets** and interests to participate. Most challenges will be easier if you are somewhat technical or creative, but in other situations it will simply require putting in some time and effort. To learn more about Bounties, go to the Builders section here.

**Comment by blrhc** [comment]
I think this has been fixed now, thank you!

**Comment by spatsochi** [comment]
> I think this has been fixed now, thank you!

Nice, thank you )
