### ISSUE TITLE
Storage Lead Reporting

### ISSUE THREAD

**Issue by bwhm** [Joystream/community-repo#195]
Currently, the reporting requirements are stated [here](https://testnet.joystream.org/#/proposals/119) and [here](https://testnet.joystream.org/#/forum/threads/409). The Council needs to nail down a specific reporting system, that defines both spotchecks and "system health" reports (feel free to change the name).
  - Spotchecks:
    - How often should the Lead perform spotchecks (eg. how many times per term)
    - What exactly should be checked, eg.
      - helios?
      - uploads?
      - downloads and playbacks speed tests?
        - note that using the storage-cli allows uploads without creating videos/channels
        - by using wget, you can download content from specific workers
        - by selecting a video where the worker was the liason, you can use [the joystream player](play.joystream.org/) to check how well it's performing
    - How should these results be presented, and where should they be posted?
  - System health report
     - How often should this be produced (eg. end of every term?)
     - What exactly should be included
       - links to the all spotchecks and writes a brief analysis/summary of the results?
       - remaining capacity for all storage providers?
       - perceived quality of service?
       - other?

Note that whatever reporting requirements are set, the Council must be prepared to take measures if they are not upheld. Also keep in mind that the requirements should be revisited.

---

Some of the proposed tasks requires the use of [the query-node playground](https://hydra.joystream.org/graphql). Some  for usage can be found [here](https://github.com/Joystream/helpdesk/tree/master/roles/content-curators/query-node-examples).

**Comment by mochet** [comment]
This has been addressed now and the documentation is within the governance subfolder
