### ISSUE TITLE
Discord video bot bugs + improvements

### ISSUE THREAD

**Issue by mochet** [Joystream/community-repo#218]
Some ideas for improvements:
* ~Show the channel name~ - realized this is already done (:
* Show the address of the channel owner (for the purpose of doing tipping more easily)
* Show the filesize (this isn't vital, but will help communicate to the council and storage WG how large files being uploaded are, this is important for scaling reasons)

Bugs:
* The first character from the description is always missing for some reason.
* Sometimes thumbnails don't show

**Comment by singulart** [comment]
The issue had been resolved. Please check my PR
