### ISSUE TITLE
Community Bounty #20 - "Github Bounty Guide"

### ISSUE THREAD

**Issue by bwhm** [Joystream/community-repo#220]
## Tags
- `Coding`
- `Content Creation`

### Description
Create a short video guide explaining how to use GitHub for submitting your bounty work.

#### Reward
USD 150 per video (1-4)
USD 50 per video (5)

#### Success Events
1. Create a brief video showing how to:
  - create a GitHub account, and fork the [Community repo](https://github.com/Joystream/community-repo) (in the browser)
  - on windows:
    - setup git using the command line
    - clone your repo, add joystream as the `upstream` remote
    - create a new local branch, and work on it...
    - ...change a file, add a new folder, add a new file
    - push your work, and open a PR to `upstream/master`
2. Same as 1, but on a mac
3. On windows, show how to:
  - fork the [Website repo](https://github.com/Joystream/joystream-org)
  - clone your repo, add joystream as the `upstream` remote
  - checkout `translations`, and translate a single page (doesn't have to be correct)
  - get the dependencies, build it locally, and show how to see your "work"
  - push your work, and open a PR to `upstream/translations`
4. Same as 3, but on a mac
5. Assuming the video guide still applies, create a voiceover in Russian for each video. You do not have to own the original to do so.

**All videos must contain a link to a forum post containing the exact commands with brief explanations in the description**

#### Resources
For 3 and 4:
A step by step guide for how to translate a single page, and review your work, can be found [here](https://github.com/Joystream/joystream-org/tree/master/src/locales/CONTRIBUTING.md).

#### Conditions
- It must be assumed that anyone watching this video doesn't have any package manager etc installed already
- The videos should be a screen recording, with the English language used on your computer
- Add brief explanations what each command does (voiced in English)
- Your video(s) must be licensed as CC0
- The video(s) must be uploaded to the [Joystream Player](https://play.joystream.org/)

#### Annihilation
- The video or written guides contain anything malicious, or "bad" links
- The video violates any licenses
- Your recording shows anything that violates the ToS or any licenses, even if it's in the background

**The below applies to the Bounty Manager/Council only, and is not necessarily relevant for the entrants.**

#### Format
Jsgenesis proposes a ["Free for All"](https://github.com/Joystream/helpdesk/tree/master/roles/council-members#free-for-all-format), where each of the Success Events can be submitted by different individuals. The BM can choose whether to set a deadline, and award the best entry within that deadline, or simply review each contribution as they come in, and award the first entry they think is good enough.

#### Review Period
Jsgenesis will have 10 days to review after the work is added as a PR to the Community Repo (the forum guide and links).

#### Status
Open

**Comment by bwhm** [comment]
@mochet @maxlevush 

Please review!

**Comment by maxlevush** [comment]
Let's add the place where the video should be uploaded. To exclude links to different cloud services
"All videos for review must be uploaded to Atlas https://play.joystream.org/"

**Comment by singulart** [comment]
My windows UI is in Russian. Shall I record the guide in Russian as well?

**Comment by maxlevush** [comment]
Opened https://testnet.joystream.org/#/forum/threads/492

**Comment by singulart** [comment]
Both workers have been paid: 
https://testnet.joystream.org/#/proposals/455
https://testnet.joystream.org/#/proposals/516

**Comment by maxlevush** [comment]
@bwhm please review

**Comment by mochet** [comment]
This bounty is no longer relevant to the new system, closing this to avoid confusion
