### ISSUE TITLE
KPI 11.5: PRs/Issues That Require Jsgenesis Action

### ISSUE THREAD

**Issue by giada42** [Joystream/community-repo#225]
Completing [KPI 11.5 ](https://blog.joystream.org/sumer-kpis/#kpi-11): Find All PRs/Issues That Require Jsgenesis Action

| #  | Repo                                                              | Link                                                                                                               | Classification       | Action Required |
| -- | ----------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------ | -------------------- | --------------- |
| 1  | [joystream](https://github.com/Joystream/joystream/issues/2516)   | [https://github.com/Joystream/joystream/issues/2516](https://github.com/Joystream/joystream/issues/2516)           | Improvements (Atlas) | Unknown         |
| 2  | [joystream](https://github.com/Joystream/joystream)               | [https://github.com/Joystream/joystream/issues/2511](https://github.com/Joystream/joystream/issues/2511)           | Social Media         | Unknown         |
| 3  | [community-repo](https://github.com/Joystream/community-repo)     | [https://github.com/Joystream/community-repo/pull/224](https://github.com/Joystream/community-repo/pull/224)       | PR                   | Fixed |
|4  | [community-repo](https://github.com/Joystream/community-repo)     | [https://github.com/Joystream/community-repo/pull/223](https://github.com/Joystream/community-repo/pull/223)       | PR                   | Fixed|
|5  | [community-repo](https://github.com/Joystream/community-repo)     | [https://github.com/Joystream/community-repo/pull/222](https://github.com/Joystream/community-repo/pull/222)       | PR                   | Fixed |
|6  | [community-repo](https://github.com/Joystream/community-repo)     | [https://github.com/Joystream/community-repo/pull/221](https://github.com/Joystream/community-repo/pull/221)       | PR                   | Fixed|
| 7  | [help-desk](https://github.com/Joystream/helpdesk)                | [https://github.com/Joystream/helpdesk/pull/105](https://github.com/Joystream/helpdesk/pull/105)                   | PR                   | Merge           |
| 8  | [hydra](https://github.com/Joystream/hydra)                       | [https://github.com/Joystream/hydra/issues/448](https://github.com/Joystream/hydra/issues/448)                     | Bug report           | Unknown         |
| 9  | [hydra](https://github.com/Joystream/hydra)                       | [https://github.com/Joystream/hydra/issues/444](https://github.com/Joystream/hydra/issues/444)                     | Bug report           | Unknown         |
| 10 | [hydra](https://github.com/Joystream/hydra)                       | [https://github.com/Joystream/hydra/issues/435](https://github.com/Joystream/hydra/issues/435)                     | Bug report           | Unknown         |
| 11 | [hydra](https://github.com/Joystream/hydra)                       | [https://github.com/Joystream/hydra/issues/420](https://github.com/Joystream/hydra/issues/420)                     | Improvements (Atlas) | Unknown         |
| 12 | [atlas](https://github.com/Joystream/atlas)                       | [https://github.com/Joystream/atlas/issues/981](https://github.com/Joystream/atlas/issues/981)                     | Bug report           | Unknown         |
| 13 | [atlas](https://github.com/Joystream/atlas)                       | [https://github.com/Joystream/atlas/pull/977](https://github.com/Joystream/atlas/pull/977)                         | PR                   | Fixed    |
| 14 | [founding-members](https://github.com/Joystream/founding-members) | [https://github.com/Joystream/founding-members/issues/34](https://github.com/Joystream/founding-members/issues/34) | Question             | Answer          |
|15|[pioneer](https://github.com/Joystream/pioneer)|[https://github.com/Joystream/pioneer/issues/867](https://github.com/Joystream/pioneer/issues/867)|Bug Report||

**Comment by singulart** [comment]
Please add "Pioneer" section to the table and add the following issue to the list: https://github.com/Joystream/pioneer/issues/867

**Comment by giada42** [comment]
@singulart  Done

**Comment by traumschule** [comment]
task 3-6 (221, 222, 224, 223) and 13 are done. @giada42 do you keep the table up to date?

**Comment by giada42** [comment]
@traumschule historically, I don't think so. What happens is that whoever draw the next list doesn't have to add the fixed issues.

**Comment by giada42** [comment]
Updated the table to show that 3, 4, 5, 6, and 13 have been fixed.

**Comment by singulart** [comment]
Triaged this list on Sep 22. The only outstanding item is no.7 (https://github.com/Joystream/helpdesk/pull/105). The others are either made by insiders (JSG personnel) or fixed/merged. Closing this issue and moving the outstanding item to the newer issue.
