### ISSUE TITLE
Community Bounty #22: KPIs Web UI

### ISSUE THREAD

**Issue by singulart** [Joystream/community-repo#280]
## Tags
`UI Design`

## Description
Create a simple but intuitive ready-to-use UI design for visualizing the current Council KPIs which are now been published as a very long and hard-to-parse HTML page https://blog.joystream.org/sumer-kpis

Despite KPIs can be very very diverse and cover the vast spectrum of tasks set to Council by JSGenesis, they have common structure and common set of properties: 

### Common information applicable for ALL KPIs of a given round, and the example values
1. Total Possible Rewards: $3600
2. Council Elected in Round: 17
3. Council Members: 16
4. Term Length: 7 days / 100800 blocks
5. Start Block/Date: #1688400 / 03.08.21
6. End Block/Date: #1789200 / 10.08.21
7. Term Summaries Forum Thread: https://testnet.joystream.org/#/forum/threads/524
8. Deadline to Submit Summary: #1818000 / 12.08.21

### Common information of any individual KPI (and example value)
1. Round number (KPI 16)
2. Title (16.1 - Proposal Clearance)
3. Reward ($200)
4. Reward Distribution (Shared) or (Individual)
5. Grading Process (Automatic or Manual)
6. Active (Full term)
7. Start Block (#1688400)
8. End Block  (#1789200)
9. Purpose (Long text)
10. Scope of Work (very long text)
11. Reward Distribution  (Long text)
12. Reporting (Long text)

## Reward
USD 250

## Success Events
Create a UI design using Joystream [brand guidelines](https://www.joystream.org/brand/guides) that would display the data from Sumer KPIs page in a nice and easy-to-navigate manner. 

Provide a link to a Figma or Sketch project containing the UI. 

Conditions

1. To be assigned to this Bounty, applicant(s) must present the high-level idea or approach to BM. 
2. The delivered project file must be self-contained and submitted for review via PR. 
3. Submitted project file must be accompanied with a set of snapshots shoowcasing the produced UI design.
2. Applicant(s) must be prepared for PR review and Bounty Manager feedback (list of changes to be made). 
3. Applicant(s) must be prepared to apply thee required changes requested via PR review.

## Review Period
Jsgenesis will have 10 days to review after the work is added as a PR to the Community Repo (the forum guide and links).

## Status
`Open`

**Comment by mochet** [comment]
Just to clarify, this bounty has not been launched/approved at this stage. It is a proposed bounty from a community member that still requires approval.

**Comment by singulart** [comment]
Proposal: https://testnet.joystream.org/#/proposals/604

**Comment by mochet** [comment]
removing draft as this was approved by the council

**Comment by singulart** [comment]
Not relevant. Closing
