### ISSUE TITLE
Community Bounty 23: Runtime Explanation

### ISSUE THREAD

**Issue by mochet** [Joystream/community-repo#289]
Approved by council: https://testnet.joystream.org/#/proposals/249

`This bounty would be for a user to create a brief description of each parameter within a runtime upgrade so that users can understand what a runtime upgrade is and isn't capable of changing.`

Requirements:
- An .md file that goes through as many attributes of a runtime upgrade as possible and gives a brief explanation of them. It is not required to explain in-depth aspects of staking, but the document should give a basic explanation of what things can actually be changed by a runtime upgrade.

Information:
- Information about the runtime is available here: https://github.com/Joystream/joystream/tree/master/runtime

Format: Open

Reward: $65

**Comment by swasilenko** [comment]
@mochet hello, is this bounty already opened? or just announced?

**Comment by mochet** [comment]
This never got done and no one expressed interest. I may relaunch it as a bounty using the `bounty module` once `olympia` launches but closing for now.

**Comment by traumschule** [comment]
I am interested, will give it a go.

**Comment by mochet** [comment]
This bounty is no longer relevant to the new system, closing this to avoid confusion

**Comment by traumschule** [comment]
Completed [here](https://github.com/Joystream/community-repo/blob/master/working-groups/operations-group/Runtime_parameters.md)
