### ISSUE TITLE
Community Bounty #25 "Joystream Superstar Blogger"-"Upload content"

### ISSUE THREAD

**Issue by MarikJudo** [Joystream/community-repo#311]
**Upload Content**
**Description**
We want to create a bounty in which the Joystream platform would develop in three directions at once.
First, Atlas video hosting would be filled with high-quality  original videos that would attract consumers from other resources
Secondly, it would be unobtrusive and effective advertising of video hosting Atlas
Thirdly, participants of the "Joystream" will be able to unite in production groups of three, to achieve more effective work in content creation
Participants must upload videos on the topic of their blog within a month.
1. The video must be creativev and original
2. Good quality.
3. Each video should support the theme of the blog. If the blog is about travel, there should be travel if cooking, cooking, etc.
4. The minimum number of videos made in a month should be three.
5. For each video posted within the created channel, you need to make a preview, which in turn should be posted in one of the social networks (vkontakte, instagram, facebook, tiktok, odnoklassniki,twitter etc) with a link to the main video  in Atlas

**Tags**
Content

**Reward**
The reward structure is decided by the Bounty Manager and the Council. We have calculated that the best form of award for the participants will look like this:

**Awards**
1st place. Team receives 9M tJoy tokens for the entire team, the distribution goes in equal shares.
2nd place. Team receives 6M tJoy tokens for the whole team distribution goes in equal shares
3. place. A team gets 1M tJoy tokens for the whole team and the distribution goes in equal shares
All other teams who pass the conditions will get 900k tJoy tokens for the whole team and the distribution goes in equal shares

**Format**
There will be an open Baunty where all users can take a part, but participants Bounty need to create a team of three people: a blogger, a creative manager and a video editor. 

**Workflow**
- Participants first fill out a participation form for the bounty
- Then create a video
- After that in the branch of discord under the icons of participants are evaluated by voting

**Success Events**
1.Get together in groups of three and assign roles to each person:
-blogger
-videomancer
-content manager
2.Fill in the participation form in the bounty.
3. Create your own unique channel with any theme, make at least three videos on it and upload them to Atlas within a month.
- The videos should have a beautiful cover
- metadata
- problem disclosure
4. Make each video a preview of at least 20 seconds and post it on any social network with a link to the main video in Atlas

**Grading**
Assessment of the video passes all users of the platform through the branch in the discord group, by placing reactions (smiles) under each video.
Only 4 types of smileys that [rate](https://drive.google.com/file/d/1ZxJto_p49T0G_sPaIO6mwda0919s15P2/view)
-General impression of the video (which includes both the participant's subjective assessment of the video itself as well as the design of its cover and the channel in general)
-The creativity of the video
-Disclosure of theme
-Quality of editing and sound
If teams decide to post additional videos to the contest in addition to the three required ones, it will give them 1 extra point for each video, thus increasing their chances of winning.
**Conditions**
-mandatory posting of previews of each video on social networks with a link to the main video in the Atlas
-mandatory team composition of three people
-created channel cover and video cover art
-Fill out the participant form
-filling in the metadata for the video
**Annihilation**
Using an existing channel in the atlas
No previews of videos on social networks
Not original videos

**Review Period**
 Voting will last from 3 days to one week, after the end of the bounty

**Notes**
Participant selected in the team position of a blogger does not necessarily have to be it. It is acceptable that for this role he attracted his familiar blogger, or an expert in any field ready to shoot. If such a situation arises, the team should notify the organizers of the Challenge in the Diskord thread

**Status**
Draft. Modifications of these rules may be modified based on Council inputs.
The rules for participants are to be made by the Council/BM, based on this issue

**Comment by mochet** [comment]
Just to clarify, this bounty has not been launched/approved at this stage. It is a proposed bounty from a community member that still requires approval.

**Comment by mochet** [comment]
This was approved, so removing draft from title.

**Comment by mochet** [comment]
This bounty is no longer relevant to the new system, closing this to avoid confusion
