### ISSUE TITLE
Community Bounty #2 - "Research and Testing of `polkadot-js extension`"

### ISSUE THREAD

**Issue by bwhm** [Joystream/community-repo#32]
## Description
After the upgrade, we have enabled the [polkadot-js extension](https://github.com/polkadot-js/extension) as part of Pioneer.

### Reward
Up to $200 can be awarded, if all success events are completed in full.

### Success Events
1. OS and Browser tests performed
   - Are Linux, MacOS, Windows all supported
   - Are Firefox, Chrome, Chromium all supported
2. Cross device tests performed
   - Does the plugin work cross device
   - Does it work cross device, cross OS and cross browsers
3. Functionality tests performed
   - What keypair types are supported
   - What are the password requirements
   - Will a key generated for a specific chain/runtime work for other chains
   - Can you import raw seeds, mnemonic seeds and/or jsons
   - Can you create new seeds and or jsons
   - Can you export seeds and or jsons

### Conditions
- A report with the results is submitted as a PR to the Community Repo.

### Annihilation
The report contains incorrect information.

### Review Period
Once the Council submits the bot, by requests for review by @bwhm and @blrhc , Jsgenesis will grade and potentially increase the fiat pool, within 72h.

### Status
Closed and completed with #67.

**Comment by traumschule** [comment]
Preliminary results. Will update the table when browser tests for windows are in ([Forum](https://testnet.joystream.org/#/forum/threads/129)).

In which folder should this be added as a file?
Could it be a mistake that `Review Period` talks about the bot?

Operating System | Linux |   |   |   | MacOS | Windows | Android |   |   | iOS
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Browser | Firefox | Tor Browser | Chrome | Chromium | Safari | Edge | Google | Brave | Tor Browser | Safari
Installable | Yes | Yes | Yes | Yes | No, see polkadot-js/extension#377. |   | Yes | Yes | No (`Experimental`) | No, see polkadot-js/extension#377.
Usable | Yes | Yes | Yes | Yes |   |   | No, invisible. | No, invisible. |   |  
  |   |   |   |   |   |   |   |   |   |  
Tested chains |   |   |   |   |   |   |   |   |   |  
https://testnet.joystream.org | X | X | X | X |   |   |   |   |   |  
https://polkadot.js.org | X | X | X | X |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |  
Algorithms | Hidden | Hidden | Hidden | Hidden |   |   |   |   |   |  
Password requirements | 6 byte | 6 byte | 6 byte | 6 byte |   |   |   |   |   |  
Cross-chain keys | Yes | Yes | Yes | Yes |   |   |   |   |   |  
Add via JSON file | Yes | Yes | Yes | Yes |   |   |   |   |   |  
Import raw seed, mnemonic | Yes | Yes | Yes | Yes |   |   |   |   |   |  
Create new seed | Yes | Yes | Yes | Yes |   |   |   |   |   |  
Backup seeds and or JSON file | Yes | Yes | Yes | Yes |   |   |   |   |   |

**Comment by mochet** [comment]
> In which folder should this be added as a file?

The best place for that would be here: https://github.com/Joystream/community-repo/tree/master/community-contributions/miscellaneous_reports

**Comment by oiclid** [comment]
`<TABLE>
<TR>
<TD>OPERATING SYSTEM</TD>
<TD>WINDOWS</TD>
</TR>
</TABLE>`

**Comment by oiclid** [comment]
OK, here are the results for the Windows tests. Two are missing though, as I wasn't sure how to test for algorithm visibility and password size. If anyone can tell me what I need to do for those two, I'll run those tests ASAP.

I imitated @traumschule 's table format.

`<TABLE>
<TR>
<TD><b>OPERATING SYSTEM</b></TD>
<TD>WINDOWS</TD>
</TR>
<TR>
<TD>Browser</TD>
<TD>Edge</TD>
</TR>
<TR>
<TD>Installable</TD>
<TD>Yes</TD>
</tr>
<tr>

<td></td>
<td></td>
</tr>
<tr>
<td>Tested Chains</td>
<td></td>
</tr>
<tr>
<td>https://testnet.joystream.org</td>
<td>Yes</td>
</tr>
<tr>
<td></td>
<td></td>
</tr>
<tr>
<td>Algorithms</td>
<td></td>
</tr>
<tr>
<td>Password Requirements</td>
<td></td>
</tr>
<tr>
<td>Cross-chain keys</td>
<td>Yes</td>
</tr>
<tr>
<td>Add via JSON file</td>
<td>Yes</td>
</tr>
<tr>
<td>Import raw seed, mnemonic</td>
<td>Yes</td>
</tr>
<tr>
<td>Backup seeds and/or JSON file</td>
<td>Yes</td>
</tr>
</TABLE>`

**Comment by traumschule** [comment]
> OK, here are the results for the Windows tests. Two are missing though, as I wasn't sure how to test for algorithm visibility ~and password size~. If anyone can tell me what I need to do for those two, I'll run those tests ASAP.

I found algorithms are only shown in the original pioneer UI, not in the extension. Password strength: I suppose it is the same: 6 characters minimum.

> OPERATING SYSTEM	WINDOWS
> Browser	Edge

Thanks! The ticket description also mentions Firefox, Chrome and Chromium tested. Can you please verify that the extension works with those. Opera and Brave could be of interest as well.

**Comment by oiclid** [comment]
> > OK, here are the results for the Windows tests. Two are missing though, as I wasn't sure how to test for algorithm visibility ~and password size~. If anyone can tell me what I need to do for those two, I'll run those tests ASAP.
> 
> I found algorithms are only shown in the original pioneer UI, not in the extension. Password strength: I suppose it is the same: 6 characters minimum.
> 
> > OPERATING SYSTEM	WINDOWS
> > Browser	Edge
> 
> Thanks! The ticket description also mentions Firefox, Chrome and Chromium tested. Can you please verify that the extension works with those. Opera and Brave could be of interest as well.
> 
> Another requirement is to test cross-chain functionality: After you created an account for joystream, the same one should work with Polkadot and Kusama as well.

@traumschule Ok. I didn't test the other browsers because only EDGE was mentioned on the Windows platform. I'll test Firefox, Chrome, and Tor. I can't test Chromium on Windowsbecause building it requires so much resources, and I am not using my computer (family member, holidays, etc). I can test Brave on Windows, though. Which is curious - I would have thought there'd be a lot more interest in testing the Brave browser, especially as it is blockchain/crypto friendly.

**Comment by oiclid** [comment]
@traumschule Also, is there a way I can reach you? Email, Telegram, or Discord would be fine. Thanks.

**Comment by oiclid** [comment]
Here are the updated tables:

`<TABLE>
<TR>
<TD><b>OPERATING SYSTEM</b></TD>
<TD>WINDOWS</TD>
<td></td>
<td></td>
<td></td>
</TR>
<TR>
<TD>Browser</TD>
<td>Chrome</td>
<TD>Edge</TD>
<td>Firefox</td>
<td>Thor</td>
</TR>
<TR>
<TD>Installable</TD>
<TD>Yes</TD>
<td>Yes</td>
<td>Yes</td>
<td>Yes</td>
</tr>
<tr>

<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Tested Chains</td>
<td>Yes</td>
<td>Yes</td>
<td>Yes</td>
<td></td>
</tr>
<tr>
<td>https://testnet.joystream.org</td>
<td>Yes</td>
<td>Yes</td>
<td>Yes</td>
<td>Yes</td>
</tr>
<tr>
<td>https://polkadot.js.org/</td>
<td>Yes</td>
<td>Yes</td>
<td>Yes</td>
<td>Yes</td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Algorithms</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Password Requirements</td>
<td>6 Bytes</td>
<td>6 Bytes</td>
<td>6 Bytes</td>
<td>6 Bytes</td>
</tr>
<tr>
<td>Cross-chain keys</td>
<td>Yes</td>
<td>Yes</td>
<td>Yes</td>
<td>Yes</td>
</tr>
<tr>
<td>Add via JSON file</td>
<td>Yes</td>
<td>Yes</td>
<td>Yes</td>
<td>Yes</td>
</tr>
<tr>
<td>Import raw seed, mnemonic</td>
<td>Yes</td>
<td>Yes</td>
<td>Yes</td>
<td>Yes</td>
</tr>
<tr>
<td>Backup seeds and/or JSON file</td>
<td>Yes</td>
<td>Yes</td>
<td>Yes</td>
<td>Yes</td>
</tr>
</TABLE>`

**Comment by oiclid** [comment]
After installing, a notification message shows on the settings icon, and clicking on the "update metadata" button in the Metadata tab doesn't clear it. It doesn't seem to affect anything, so far seems to only be annoying.

**Comment by mochet** [comment]
> After installing, a notification message shows on the settings icon, and clicking on the "update metadata" button in the Metadata tab doesn't clear it. It doesn't seem to affect anything, so far seems to only be annoying.

A window is supposed to pop up and add metadata to the extension as I understand, but I'm not sure why it doesn't happen on Joystream. @traumschule it's probably important to mention that in the notes (you can see the normal behavior if you use Kusama or Polkadot chains)

**Comment by oiclid** [comment]
Updated the table to include results for Brave (it works) and Opera (it doesn't) on Windows.

**Comment by mochet** [comment]
The proposal has been approved: https://testnet.joystream.org/#/proposals/87
I will set this for review as soon as the additional information has been merged

**Comment by traumschule** [comment]
> Updated the table to include results for Brave (it works) and Opera (it ~doesn't~ does also, just takes a little longer) on Windows.

In the table above Opera has `No` in every cell.
