### ISSUE TITLE
Community Bounty #26: "Joystream and other video platforms" videos

### ISSUE THREAD

**Issue by katerina510** [Joystream/community-repo#342]
(After discussing with the Council [(link)](https://testnet.joystream.org/#/proposals/562), it was decided to propose this as an official Bounty)

I think, we can gain really useful members, if we start talking about Joystream on other decentralized video platforms. People here already know about decentralization and understand why is it important.
3 popular platforms already on mainnet are: Theta.tv, Odysee and Dtube. I propose to make a Bounty for uploading videos about Joystream and(or) its comparison to other platforms (decentralized or not) on these 3 platforms. Other popular decentralized platforms can also be used.
I made a research and now I know why we are better than other platforms and Youtube. [Research](https://medium.com/@katerina510/joystream-vs-other-decentralized-video-platforms-and-youtube-73db4c106431). It can be used in video production for this Bounty.

**The rules are the following :**

* The video should be about Joystream itself and(or) its comparison to other video platform(s) (decentralized or not).
* The video should NOT be agressively promotional, its main purpose is just to make a comparison or talk about Joystream to the people who might be interested without trying to impose on them.
* Videos that would be interesting only for experienced members of Joystream (github guideliness, for example) or very short videos (like 7-second videos for Sprocket - JSlogo) will not be accepted.
* The video should have a good title (again, not agressively promotional), thumbnail and description.
* You can use the above mentioned research for reference, but you should be creative and not just read the text of the research. Remember, you will get more rewards for high quality videos.
* The video should participate in Bounty 18 and be already graded.
* The video should be uploaded to Theta.tv, Odysee, Dtube or all of them (or other popular decentralized platforms).
* The link(s) to the video, uploaded to these platforms, as well as the link to the video in Atlas, should be provided on the forum thread for this Bounty.
* If you upload a video to all 3 above mentioned platforms (or other popular decentralized platforms), you will get a reward equal to the reward you got for this video in Bounty 18. If you upload to 2 platforms, you will get ⅔ and for 1 platform ⅓ of the reward.

**Duration** : while Bounty 18 lasts (may be longer, then the videos will be graded separately, not within Bounty 18)

**Review period** : Videos should be reviewed no later than 7 days after submitting.

**Budget** : 500$ a week is a maximum (maybe less, depends on funding capabilities)

**Comment by mochet** [comment]
@katerina510 is there an approved proposal for this bounty?

**Comment by laura2727** [comment]
@mochet @katerina510 I'm not sure, but it looks like this Bounty has been closed. (It didn't start)

**Comment by mochet** [comment]
This bounty is no longer relevant to the new system, closing this to avoid confusion
