### ISSUE TITLE
23.II-2 PRs/Issues That Require Jsgenesis Action

### ISSUE THREAD

**Issue by singulart** [Joystream/community-repo#361]
|#| Repo            | Link | Classification | Action Required |
|-|---------------------|--------------|--------------|----------|
|1| [Helpdesk](https://github.com/Joystream/helpdesk) |  [Update ReadMe](https://github.com/Joystream/helpdesk/pull/105) | PR, Helpdesk | Needs Review |
|2| [Hydra](https://github.com/Joystream/hydra) |  [Documentation for developer contributions](https://github.com/Joystream/hydra/issues/218) | Issue | Needs Review |
|3| [Helpdesk](https://github.com/Joystream/helpdesk) |  [Correction of typos, inaccuracies and broken link](https://github.com/Joystream/helpdesk/pull/108) | PR, Helpdesk | Needs Review |
|4| [Helpdesk](https://github.com/Joystream/helpdesk) |  [Corrected wrong links, grammar and punctuation, corrected and added info](https://github.com/Joystream/helpdesk/pull/109) | PR, Helpdesk | Needs Review |
|5| [Helpdesk](https://github.com/Joystream/helpdesk) |  [Fix channel by id query example](https://github.com/Joystream/helpdesk/pull/106) | PR, Helpdesk | Needs Review |
|6| [Atlas](https://github.com/Joystream/atlas) |  [Delete channel](https://github.com/Joystream/atlas/issues/1026) | Feature Idea | No Assignee |
|7| [Atlas](https://github.com/Joystream/atlas) |  [Audio Mode](https://github.com/Joystream/atlas/issues/988) | Feature Idea | No Assignee |
|8| [Atlas](https://github.com/Joystream/atlas) |  [Figma Reorg](https://github.com/Joystream/atlas/issues/920) | Housekeeping | No Assignee |
|9| [Founding Member program](https://github.com/Joystream/founding-members) |  [Updating information Reorg](https://github.com/Joystream/founding-members/pull/74) | Housekeeping | No Assignee |
|10| [Joystream.org](https://github.com/Joystream/joystream-org) |  [Bug: broken link to whitepaper on blog page](https://github.com/Joystream/joystream-org/issues/348) | Broken Link Fix | No Assignee |
|11| [Community Repo](https://github.com/Joystream/community-repo) |  [add joystream-leaderboard-bot](https://github.com/Joystream/community-repo/pull/237) | Code Contribution | To be Merged |
|12| [Community Repo](https://github.com/Joystream/community-repo) |  [Storage Notifier Bot for discord](https://github.com/Joystream/community-repo/pull/241) | Code Contribution | To be Merged |
|13| [Community Repo](https://github.com/Joystream/community-repo) |  [KPI 14.12 API Scripts Maintenance](https://github.com/Joystream/community-repo/pull/245) | Code Contribution | Needs JSG Review |
|14| [Community Repo](https://github.com/Joystream/community-repo) |  [Combined Telegram & Discord Bot ](https://github.com/Joystream/community-repo/pull/307) | Code Contribution | Needs JSG Review |
|15| [Community Repo](https://github.com/Joystream/community-repo) |  [Implementation of Joystream Scoring Periods Telegram/Discord BOT](https://github.com/Joystream/community-repo/pull/331) | Code Contribution | To be Merged |
|16| [Community Repo](https://github.com/Joystream/community-repo) |  [Update tokenomics report script](https://github.com/Joystream/community-repo/pull/332) | Code Contribution | To be Merged |
|17| [Community Repo](https://github.com/Joystream/community-repo) |  [KPI 21.8: New folders structure](https://github.com/Joystream/community-repo/pull/346) | REPO REORG | To be Merged |

Predecessor issue: https://github.com/Joystream/community-repo/issues/225

**Comment by traumschule** [comment]
@bwhm @blrhc Somehow there was a big delay here. I checked: except 2 and 7 all seems resolved.
