### ISSUE TITLE
New Telegram Bot bugs + improvements

### ISSUE THREAD

**Issue by mochet** [Joystream/community-repo#38]
Since the new bot has been implemented, we can use this issue to discuss bugs + potential improvements.

The old issue is here: https://github.com/Joystream/community-repo/issues/10

**Comment by mochet** [comment]
Some bugs so far:
- When a new proposal is announced, the previous proposal is also announced.
- Council elections are not announced (this seemed to work in the test channel, so not sure why it stopped working)

Annoyances:
- When a thread is made, it announces the creation of the thread and then immediately after announces the content of the first post.

**Comment by traumschule** [comment]
I believe all above are fixed now

**Comment by mochet** [comment]
> I believe all above are fixed now

Judging by the Joystream Governance channel I think you are correct.
The only bug I've noticed is that Spending Proposals always seem to "failed to be executed" when they have actually succeeded.

**Comment by mochet** [comment]
This has mostly been solved for now.
