### ISSUE TITLE
Community Bounty #27: Official music theme

### ISSUE THREAD

**Issue by agrafen** [Joystream/community-repo#384]
**Description**
I want to create a bounty for creating official background music for a videos (which can be used in a video related  to the project).

- The demo should ideally contain:
1. Jingle
2. Quiet background part (for speech),
3. Loud, for video without speech
4. The most dynamic part (drop), if you need to show something cool in the video.
- Because this is a demo, then you can get by with the presence of points 1-2 or 2-3.
- Upload the recording as a video (with picture) to the atlas
- Add the source to the github
- Make sure that there are no copyright problems (samples, sounds, synth, melodies)
- Must be licensied for free use
- The length of the each music fragment should be not less then 40 seconds (excluding jingle)

**Tags**
Content

**Budget**
400$ is a maximum

**Awards**
1nd - $150 (up to 300$ fo really good content)
2nd - $50
3nd - $50
places will be determined by community vote

**Duration**
1 month

[proposal for councils](https://testnet.joystream.org/#/proposals/606)

**Comment by mochet** [comment]
This was approved by the council via proposal, removing DRAFT from the title.

**Comment by bwhm** [comment]
> Well, or just indicate that you need to transfer the source code to receive the award?

I guess it would be nice to have it available on the platform, but then it would have to be a video. I think you're right, they should be on github as well. However, they don't have to transfer ownership of anything. The only requirement is that it's license free!

**Comment by agrafen** [comment]
@bwhm

I also think that in addition to the source, need to provide a recording in good quality.

**Comment by agrafen** [comment]
@bwhm

Can officialy launching or something else? =)
