### ISSUE TITLE
Council Workflow (WIP)

### ISSUE THREAD

**Issue by mochet** [Joystream/community-repo#44]
This is a document that we can use to illustrate what a successful council should achieve during any given council session and regardless of KPIs. As this is still WIP it will be an issue and later can be turned into an actual document.

As anyone can submit proposals it may be that work is done outside of council members themselves.

# Council Workflow

## Council Start
* Hire Council Secretary / any other necessary roles

## Council Run
* Spot checks for working groups

## Council End
* Council Report
* Tokenomics Report

**Comment by freakstatic** [comment]
Good idea! 😁

**Comment by mochet** [comment]
This is sort of solved by KPIs but would be good to have at a later stage.
