### ISSUE TITLE
KPI: 5.6 Council Status Report

### ISSUE THREAD

**Issue by bwhm** [Joystream/community-repo#45]
With 4 Council terms completed, it's time for a review of the KPI system and Council performance thus far.

## Council Summary
For each Council term:

| memberId | handle     | ownStake | otherStake | voting history     | Reward |
|-----------|-----------|-----------|-----------|-----------|-----------|
| `<i>`        |`<handle>`| `<a>` tJOY |`<b>` tJOY |  `<n>/<m>`| `<c>`tJOY <d>USD |

Where the CM voted on `n` proposals out of  `m` possible.

And an overview:
| memberId | handle     | councils | voting history     | Rewards | 
|-----------|-----------|-----------|-----------|-----------|
| `<i>`        |`<handle>`|  `<1,2,3,4>` |  `<n>/<m>`| `<c>`tJOY <d>USD |

## Thoughts for the Future
Create a "survey" from all previous CMs (and anyone else that wants to weigh in). The answers should be made on chain in the forum, but anonymous replies can be made in DMs on telegram (to Martin and/or Ben).

### Council and Elections
1. How many elections have you participated in as a candidate?
2. What did you do to get promotion?
3. How many of those did you get elected?
4. How many elections have you participated in as a voter, but not a candidate?
5. Do you think the council size should be increased/reduced? Why?
6. Do you think the council term should be longer/shorter Why?
7. Do you think any of the other stages should be longer/shorter Why?
...

### Council communication
1. Has it been difficult to communicate with other CMs?
2. Has there been much of a "need" to communicate with other CMs?
3. Has there been any communication with other CMs outside of forum and/or telegram?
4. Would it be easier if the Council had a dedicated communication channel? If yes: 
   - should it still open for all?
   - should it be "read only" for non-CMs?
   - should it be "secret"
...

### KPIs
1. How much time (estimate) did you spend on direct or indirect tasks related to being a CM?
2. If you have been in multiple terms: Has the workload/time spent trended up or down?
3. Which tasks takes the most time?
4. Are there any KPIs that seems especially meaningful?
5. Are there any KPIs that seems especially meaningless?
...

### Bounties
1. Why has it proven challenging to complete Bounties?
   - (compensation? tasks?)
2. Would it help if Jsgenesis changed policy from a "few and important Bounties" to "many and fun"
3. What kind of Bounties would you like to see?
4. What could be done to promote Bounties?
...

---

Comments are welcome!

**Comment by mochet** [comment]
@bwhm it might be worth asking for feedback on the size/duration of council terms + the duration of the election stages.

**Comment by bwhm** [comment]
> @bwhm it might be worth asking for feedback on the size/duration of council terms + the duration of the election stages.

Good point! Added :)

**Comment by mochet** [comment]
This was completed, so I will close the issue.
