### ISSUE TITLE
External Stats Website (WIP)

### ISSUE THREAD

**Issue by mochet** [Joystream/community-repo#50]
As Pioneer is quite complicated to upgrade it may be worth investigating making a 3rd party website which can take chain information and populate it with statistics. One example of this is https://siastats.info/

I couldn't find any examples that show stats for a council or governance system, but maybe having some of the ideas here on a 3rd party website would work: https://github.com/Joystream/community-repo/issues/18

**Comment by bwhm** [comment]
Hey,

Yes something like this would definitely be fun to have. It's kind of what we'd want the current tokenomics page would do, but before the query-node indexes the relevant modules, it's pretty much impossible. The query-node will work with all things content starting with Babylon, but the rest will be added in stages...

**Comment by traumschule** [comment]
I started https://joystreamstats.live

Does anyone want to create wireframes or a list of data points? So long I can start adding info from https://pioneer.joystreamstats.live/#/tokenomics

**Comment by mochet** [comment]
> I started https://joystreamstats.live
> 
> Does anyone want to create wireframes or a list of data points? So long I can start adding info from https://pioneer.joystreamstats.live/#/tokenomics

This is a great start! I can put together some ideas of what would be nice to have in the next few days.

**Comment by blrhc** [comment]
Will there be a GitHub repo for this at some point?
Excellent work @mochet and @traumschule btw!

**Comment by mochet** [comment]
> Will there be a GitHub repo for this at some point?
> Excellent work @mochet and @traumschule btw!

Thanks. I believe @traumschule is aiming to submit a PR soon!

**Comment by traumschule** [comment]
> Will there be a GitHub repo for this at some point?

Here you go: https://github.com/traumschule/joystreamstats

**Comment by mochet** [comment]
this has been solved
