### ISSUE TITLE
PRs created by @dependabot

### ISSUE THREAD

**Issue by singulart** [Joystream/community-repo#500]
| PR#  | Can be merged?  | Version bumped  |  Tool | Comments  |
|---|---|---|---|---|
| [494](https://github.com/Joystream/community-repo/pull/494)  | Yes  | Minor  | joystream-api  |   |
| [395](https://github.com/Joystream/community-repo/pull/395) |  No, requires impact analysis | **Major**  | joystream-api  |  [Upgrade Guide](https://github.com/node-fetch/node-fetch/blob/main/docs/v2-UPGRADE-GUIDE.md) |
| [394](https://github.com/Joystream/community-repo/pull/394)  | Yes  | Minor  | storagesize-bot  |   |
| [393](https://github.com/Joystream/community-repo/pull/393)  | Yes  | Minor  | joystream-scoring-period-bot  |   |
| [392](https://github.com/Joystream/community-repo/pull/392)  | Yes  | Minor  | joystreamvideobot  |   |
| [374](https://github.com/Joystream/community-repo/pull/374) |  No | **Major**  | joystream-api  |  PR against the old repo structure, duplicates #395 |
| [373](https://github.com/Joystream/community-repo/pull/373) |  No | Minor  | storagesize-bot  |  PR against the old repo structure, duplicates #394 |
| [372](https://github.com/Joystream/community-repo/pull/372) |  No | Minor  | joystream-scoring-period-bot  |  PR against the old repo structure, duplicates #393 |
| [371](https://github.com/Joystream/community-repo/pull/371) |  No | Minor  | joystreamvideobot  |  PR against the old repo structure, duplicates #392 |

**Comment by traumschule** [comment]
LGTM! @mochet Let's merge 494, 395, 394, 393, 392 and close the rest.

**Comment by mochet** [comment]
> LGTM! @mochet Let's merge 494, 395, 394, 393, 392 and close the rest. Proposal: https://pioneer.joystreamstats.live/#/proposals/862

thanks, will do!

**Comment by mochet** [comment]
completed!
