### ISSUE TITLE
Community Bounty #5 - "Joystream Telegram Sticker pack"

### ISSUE THREAD

**Issue by bwhm** [Joystream/community-repo#52]
## Description
Create a Joystream branded sticker pack for Telegram.

Telegram allows for custom sticker packs to be made. These can spice up the conversation a little, and allows the Joystream Community to let their creativity and design show!

### Reward
Up to $400 when first opened 12.11.20 with three success events.
Note that new success events can be added, after event 1 is complete, and sets the parameters. This may also lead to adjusting the rewards

### Success Events
The first needs to be completed before the terms, rules and specifics can be determined.

1. Provide details on how to create a sticker pack on Telegram - $100:
   A report answering the following questions is made:
   - What are the steps involved for creating a sticker pack?
   - Are there any costs associated with this?
   - How should this bounty be organized?
2. Produce a sticker pack with at least 10 Joystream branded/related stickers - $300 (max):

### Conditions
- Artwork is made available in the Community Repo
- Must be in good taste, and related to the project
- Grading for success event 2 will be highly subjective.

### Annihilation
Stickers contain artwork that violates any licenses or copyrights.

### Review Period
Once the Council submits the report from success event 1, and @bwhm and @blrhc is assigned to review, Jsgenesis will grade within 72h, and update for the next event(s).

### Status
[Open](https://testnet.joystream.org/#/forum/threads/169).

**Comment by oiclid** [comment]
@bwhm By "closed" does that mean are you are no longer accepting entries?

**Comment by bwhm** [comment]
> @bwhm By "closed" does that mean are you are no longer accepting entries?

It was just a copypasta error, sorry about that :D

**Comment by oiclid** [comment]
Alright, thanks.

**Comment by bwhm** [comment]
@oiclid 
Have a look at the link btw! It should help you know how to proceed...

**Comment by botzmann** [comment]
Stickers
https://t.me/addstickers/joystream54
BOTZMANN 5EA1RhYg4NCJp4qfvTYNzVCSGF5X7VF2VeKFm21kTbqfoZxe

**Comment by mochet** [comment]
this bounty has been completed
