### ISSUE TITLE
KPI 6.6: Content Sourcing

### ISSUE THREAD

**Issue by bwhm** [Joystream/community-repo#53]
With the introduction of Atlas as part of the Babylon release facilitating easier and more engaging content consumption, it is becoming ever more important that we populate our content directory with appealing content, for a variety of reasons. These are not limited to: increasing awareness of the platform, allowing us to create a more accurate simulation of the content types and characteristics available on mainnet and for other community purposes.

For this reason we have devised a KPI asking the Council to identify some of the best ways to obtain such content. 

We are hoping the Council will suggest creative solutions to solve this issue, among which might include using Spending Proposals to fund content by selected creators, identifying new sources of public domain content, remixing existing open content and other more creative suggestions...

All content sourced will need to be appropriately licensed. Atlas will natively support Public Domain and Creative Commons-licensed content, but of course content using any license which allows distribution on platforms such as Joystream will be permitted.

At this early stage in the process the only deliverable required will be a report exploring some of the feasible methods for obtaining these new content items. These methods should be outlined in detail in order to allow future Councils to act on some of the most promising suggestions made.

We are mainly looking to focus on quality rather than quantity in this KPI, though any technique which will "enrich" the content directory should be explored in detail in the Council's report.

**Comment by mochet** [comment]
This was completed so will close the issue.
