### ISSUE TITLE
What are the most essential notifications?

### ISSUE THREAD

**Issue by mochet** [Joystream/community-repo#564]
We have several bots that provide network notifications and act as crucial channels of information for all participants.
- If you were limited to a single channel, what would be the most crucial notifications of on-chain events?
- Which events are critical to know? Which are not?

**Comment by Mus156** [comment]
Hello! My name is Vladislav, (discord -Vladislav#7137). The following notifications are most important to me:
1. Messages about the dates of upcoming events (for example: testnet launch date; filing dates any applications for participation with links to the application form).
2. Messages about network updates (to always stay in the current version of the network).
3. Messages about important events (for example, the conclusion of new partnerships).

In my opinion, it would be convenient to receive them by e-mail.
