### ISSUE TITLE
Things changing with Olympia - WIP

### ISSUE THREAD

**Issue by mochet** [Joystream/community-repo#623]
- no more need for making election threads. Olympia will have an inbuilt automatic way for council member applicants to announce their goals
- council blog module (not sure)
- Staking system for WGs and more is changing significantly, this will require quite a bit of time and attention to educating old + new users. It is far more complex.

**Comment by traumschule** [comment]
[@joystream/types 0.18.0](https://github.com/Joystream/joystream/blob/olympia/types/package.json) requires another upgrade of all scripts

**Comment by mochet** [comment]
Forgot I made this. Closing and put anything worthwhile into https://github.com/Joystream/community-repo/issues/714
