### ISSUE TITLE
Validator Spot Check - WIP

### ISSUE THREAD

**Issue by mochet** [Joystream/community-repo#63]
The validator role largely manages itself and the council can only control the number of validators, so a spot check for this role might look more like an informational report than a typical spot check. It should include information that would matter to nominators, people seeking to become validators and most network participants.

This would largely take the form of a script that can take a start and end blockheight and provide statistics on those blocks. Other parts of it would be based on more informal sources like user feedback on the forums.

It could also include a general conclusion about how the validators and nominators are doing.

The current tools available are:
- Joystream Tokenomics page: https://testnet.joystream.org/#/tokenomics
- Joystream Validators page: https://testnet.joystream.org/#/staking
- Polkadot Telemetry: https://telemetry.polkadot.io/#list/Joystream

Some ideas:
### Stake
- The proportion and distribution of commission rates (ex. "How many validators have a 80-90% vs 90-100% commission rate?")
- The proportion and distribution of validator stake (ex. "How many validators have staked  500k-1m JOY vs 1-2m JOY")
- The proportion and distribution of nominator stake (ex. "How many nominators have staked 500k-1m JOY vs 1-2m JOY")
- The proportion and distribution of total stake (ex. "How many val+nom have staked 500k-1m JOY vs 1-2m JOY")
- The proportion of nominator stake vs total stake vs total issuance

### Constant values
- What the ideal staking amount is, and what it currently is
- Given stake>total issuance, what is the current inflation rate?

### Financials
- At the current exch. rate, how much is each validator and nominator making?
- How much the role is paying to each validator, at current rates, for the next month (this is slightly complicated because you would also need to look at how nominators get rewards, which isn't shown in Pioneer yet)
- How many validators, when considering nominator cut are making enough to cover likely server costs?
- How much a server to run the role is likely to cost (this is currently largely tied to database size)
- The current size of the blockchain database, how fast is the chain growing

### Decentralization & Performance
- The geographical distribution of nodes (if we can get IP addresses of all known nodes, it might be possible to use some geolocation script to give an idea of what countries are hosting nodes. The idea with this is to try and know if validators are too centralized)
- The performance of validators (ex. how well are the validators doing to keep the network running consistently, judged by average blocktimes)

### Role information
- How many waiting validators have there been over time
- How many non-validating nodes are there vs validating nodes
- How many nominators vs validators are there

Other information that would be good to know, but might be harder to find:
- How many validators or nominators were slashed recently?
- How many tokens were slashed recently?
- At the current exch. rate, how much is each nominator making?
- How much bandwidth does a validator use?
- Has finalizing had any long lag periods?
- How many blocks had much longer than average periods to be produced (ex. if a block should take 6 seconds to be produced, how many blocks took >10s to produce, also is it possible to know which validators were responsible for these delays?)

**Comment by mochet** [comment]
We can also measure time dilation during each council session.
For example if the average block time should be 6s then a council session is 201,600 then a council session should be 1209600 seconds long, or 14 days. If we calculate the time period that a council session takes and it is more or less than 201,600 then we can calculate how much it drifted.

**Comment by traumschule** [comment]
Joystream/pioneer#3819
