### ISSUE TITLE
joystreamstats.live improvements - WIP

### ISSUE THREAD

**Issue by mochet** [Joystream/community-repo#70]
The basic site is up and seems great.

A few potential additions/improvements:
- A way to list proposals by author and maybe some stats about % of proposals passed/failed/slashed by that author
	- Help to build the reputation of proposal creators
- A way to list proposals by type (ex. text/spending/ValidatorCount) and maybe some stats
	- Help to identify how each proposal type is differently recieved by the council
- A "tools" section that could have some easier ways of calculating role payments (ex. if `storage lead` is paid 23146 JOY per 3,600 blocks, how much is that in dollars at current exchange rate)

**Comment by traumschule** [comment]
> * A way to list proposals by author and maybe some stats about % of proposals passed/failed/slashed by that author
>   
>   * Help to build the reputation of proposal creators
> * A way to list proposals by type (ex. text/spending/ValidatorCount) and maybe some stats

https://joystreamstats.live/proposals now supports sorting by clicking on the table header and filtering by author and proposal type.
   
> * A "tools" section that could have some easier ways of calculating role payments (ex. if `storage lead` is paid 23146 JOY per 3,600 blocks, how much is that in dollars at current exchange rate)

https://dev.joystreamstats.live/mint has a first draft how this could look like.

Don`t hesitate to add your ideas!

**Comment by bedeho** [comment]
Checked it out, looks really great! Very impressed.

**Comment by mochet** [comment]
Another interesting thing to start looking at would be elections, specifically:
- which accounts voted and how much did they vote for across all elections or individual elections?
- which successful and unsuccessful council members received votes, and for how much? (this should be looked at across single elections and multiple elections in order to establish reputation)
- maybe a ratio for each election showing the relationship between ownstake + voterstake
- maybe a ratio for each election showing the relationship between voterstake (ex. "from total voterstake, how much did `userA` vote in percentage?")

**Comment by mochet** [comment]
I also think one "end goal" for the stats website should be to establish reputation of actors on the platform.

So for any particular given username, a user should be able to click on their username and establish:
- how many times they have been a council member, and how many times have they applied to be a council member unsuccessfully
- their voting history for proposals
- they voting history for elections and the history of how many times they've been voted for on elections
- their history of creating proposals
- their history of successful/unsuccessful proposals
- their history of spending proposals specifically (ex. "how many tokens has this user received via spending proposals")
- their forum history
- their channels/videos
- their history of being a lead in a working group (both successful and unsuccessful applications)
- their history of being a worker role in working groups (both successful and unsuccessful applications)

Some of these may not be achievable right now without a query node

**Comment by mochet** [comment]
@traumschule An improvement for the landing page would be to have a link to all the prominent pages of the site, for example, the calendar, council page. Currently, a user has to navigate through several pages to get to these sections (or they may be currently unlinked).
