### ISSUE TITLE
Community Bounty #6 - "Increase Validator Set Research"

### ISSUE THREAD

**Issue by bwhm** [Joystream/community-repo#71]
## Description
Research the costs and parameter changes associated with increasing the Validator count substantially.

With a new incentives program to be disclosed shortly, we want to increase both the visibility of the platform, and open up for more people to contribute and participate on the platform. We believe running a node, and potentially becoming a validator, is a good way of getting started, and reaching the front page of the [Polkadot Telemetry](https://telemetry.polkadot.io/#/Polkadot) could get some eyeballs.

### Reward
Up to $200 when first opened 17.01.21 with two success events.
Note that more success events, or just expanding on the two, can be added later. This would also lead to adjusting the rewards.

### Success Events
Currently, the max validator count is 42. These report should focus on the consequences of bumping this to:
- 100
- 200
- 300
- 500
 
1. Produce a report estimating the costs, for the validators themselves and other tJOY holders, associated with a larger validator set. - $100:
   - What is a good estimate of the (current) running costs for a validators? This assumes running a VPS from some of the bigger actors around.
   - What is the weekly "cost" for the platform (in terms of tJOY and USD) the last 4 weeks?
   - How much of the returns are not cashed out?
   - Has there been any slashes in this period?
 
Note that with a current `historyDepth` of 336 eras (~14 days), some of these questions will require you to query an archival node (such as the hosted one) with `at`. Eg.
`await api.query.staking.at.erasValidatorReward(blockHash, eraIndex)`

2. The report includes a table with the proposed parameters for a set of potential 'Max Validator Count' values. - $100:
   - How much would the required returns be (in tJOY and USD) pr week for each of the proposed validators counts to stay profitable?
   - What would the runtime parameters need to be set to to account for this?

For help with these calculations: Feel free to make a copy of this [spreadsheet](https://docs.google.com/spreadsheets/d/13Bf7VQ7-W4CEdTQ5LQQWWC7ef3qDU4qRKbnsYtgibGU/edit?usp=sharing), and play around with the values:

### Conditions
- The report is issued as a PR to the Community Repo

### Annihilation
NA

### Review Period
Once the Council submits the report, and @bwhm and @blrhc is assigned to review, Jsgenesis will grade within 72h.

### Status
[Completed - $200](https://github.com/Joystream/community-repo/pull/77)

**Comment by traumschule** [comment]
I started working on this and am happy about input to questions below. This is WIP.

# 1. 
- What is a good estimate of the (current) running costs for a validators? This assumes running a VPS from some of the bigger actors around.

The costs for a VPS to run a reliable and stable validator node range from 5 to 15 $ / month depending on location and hosting provider.
Hardware demands are around 40 to 50% constant CPU load for a 2.5 GHz core and at least 19 GB of disk space.

- What is the weekly "cost" for the platform (in terms of tJOY and USD) the last 4 weeks?

The total reward grew constantly from 18426 two weeks ago up to 20875 JOY per hour which is related to increasing amount staked.

Current costs amount to 157$ per week (3.4 M tJOY).

 time | payout JOY | payout $ | payout $ / validator
-- | -- | -- | -- 
per hour |    20.7 K  |       0.93  | 0.02
per day |     496.8 K  | 45  | 0.15
per week |    3.4776 M | 157  | 3.7
per month |   13.9 M | 628 | 15

- How much of the returns are not cashed out?

TBD. Who has an idea how to determine this?

- Have there been any slashes in this period?

TBD

# 2. 
- How much would the required returns be (in tJOY and USD) pr week for each of the proposed validators counts to stay profitable?

Please check https://joystreamstats.live/mint for logical errors.

- What would the runtime parameters need to be set to to account for this?

Which runtime parameters affect `staking.erasValidatorReward`?

**Comment by mochet** [comment]
> * How much of the returns are not cashed out?
> 
> TBD. Who has an idea how to determine this?

You could look at the history of validators and which validators have self staked (meaning their validator rewards increase their own stake) and who have not reduced `ownStake` the entire time. It may be that some have decreased and then later increased their `ownStake` via other tokens (like tokens from a spending proposal).

There is a lot more that could looked at when considering this, but this is the only way I can think of that can give a direct answer.

The problem is that this relies a lot on consistent validators with a long history because a validator that stopped the role would have reduced their stake to 0.

You could also investigate the number of validators that operate by increasing their own stake vs not increasing.

**Comment by bwhm** [comment]
[Closed - $200](https://github.com/Joystream/community-repo/pull/77)
