### ISSUE TITLE
First Council on Olympia!

### ISSUE THREAD

**Issue by bwhm** [Joystream/community-repo#731]
The below should be soon as a living document until the Council is actually elected. At this stage, it's basically just a "todo" list, covering things we need from the Council and the Community to get going fully!

# First Council
The Council incentives on the Olympia will rely on more on metrics than the previous KPI system. However, as we are starting on a new chain, it would be quite difficult and unfair to measure the quality of service provided by the Working Groups in any meaningful way. For that reason, the first set of incentives will likely look more like KPIs, and require more subjectivity in grading, but with a couple of "teasers" of what's to come sprinkled in.

As before, we will in some cases "interfere" in the Council election, by putting our stake behind a subset of applicants. As will become evident further down, this is to ensure that we have some rotation, and leaves some "room" for newcomers!

Somewhat unrelated, but useful to know:
The helpdesk will be discontinued, and replaced by the [Joystream Handbook](https://joystream.gitbook.io/testnet-workspace/). There's a fair amount of holes in it, but these will be plugged through a collaborative effort during the first Council Term.

## Council
The main overarching goals can be boiled down to:
1. Ensure the Forum categories are deployed ASAP after launch
2. Ensure Content Migration goes smoothly
3. Ensure uploads and downloads are working at a "satisfactory" level after the migration
4. Ensure account `5EtQWE72D146EpujfoRbVJayC5Bmw19S2YrY8UinFENategX` has available membership invitations at all times.
5. Have "greeters" (from the Human Resources WG) in place on discord as quickly as possible!
6. Elect Leads, and set budgets for all roles

As neither the Forum, nor content consumption/creation will work at launch, it's natural that it's a high priority.

## Working Groups
Some general notes:
- One of the many things the Council will be measured by, directly or indirectly, is their focus on giving new people a chance to tackle roles - both as Workers (and eventually) as Leads, without sacrificing on quality.
  - Hiring the "wrong" person initially isn't the end of the world.
  - The Council will be graded on the "quality" of the Lead openings being approved, so creating them seems reasonable.
- The incentives will (at least should) shape the SoW, budgets and workflow for each WG, so creating too detailed SoW's at this point is likely unnecessary.

Instead of going alphabetically, the WGs are sorted roughly in order of priority/urgency for the launch and migration.

### `Content`
1. Hire a Lead within block `#50400` - the sooner after the election, the better!
2. Note that no action is required by the Lead for the content migration, apart from getting hired (video and channel categories can't be deployed without a lead)
3. Set a budget for the group (for the remainder of the Term + 1 day)

### `Storage Providers`
1. Hire a Lead within block `#50400` - the sooner after the election, the better!
2. Ensure the Lead follows the "protocol" outlined [here](https://github.com/Joystream/community-repo/issues/726) (will be revised) for the content migration.
3. Ensure the Lead "cleans up" after the migration, and deploys a solid system so that we have as few failed uploads as possible as soon as Atlas "reopens" after the migration.
4. Set a budget for the group (for the remainder of the Term + 1 day)

### `Distribution`
1. Hire a Lead within block `#50400` - the sooner after the election, the better!
2. Ensure the Lead follows the "protocol" outlined [here](https://github.com/Joystream/community-repo/issues/726) (will be revised) for the content migration.
3. Ensure the Lead "cleans up" after the migration, and deploys a solid system so that we have content served as quickly and seamlessly as possible as soon as Atlas "reopens" after the migration.
4. Set a budget for the group (for the remainder of the Term + 1 day)

### `Forum`
1. Hire a Lead by block `#44400` (Election complete + 2h!), to initiate some some categories. Note that:
  - the Lead could be a temporary one, solely for creating the initial categories. Required: `categoryId` 1: (the first one) `Bounties`
    - all new Bounties created will "autmatically" create a new thread in said category, so be careful with naming/description
    - create some other reasonable categories as well
  - although categories CAN be changed, large changes will mean lots of cleanup for the new Lead!
2. Set a budget for the group (for the remainder of the Term + 1 day)
3. Create a draft SoW for the Lead and Workers of the Group
  - This should include any reporting requirements you think is reasonable
  - Note that the "real" incentives, which will go live from as the second Council is elected, will likely shape the above
4. If applicable, hire a "real" Lead by block `#72000`.
  - Consider asking the applicants to outline their initial category structure.
5. Ensure the Lead creates a "good" set of categories, that covers what is needed for a blockchain based video platform DAO!

### `Membership`
1. Create an opening at launch (within block `#44400`), ping Martin and Ben (`@bwhm#6514` and `@blrhc#0162` on Discord), and hire member `3439` within `1200` blocks after that member has applied! This role will initially be held by a key held by Jsgenesis, but apart from running/maintaining the membership faucet, no further actions will be taken by us.
2. Create a proposal to give the Membership Lead a good amount of membership invitations for the faucet, and monitor the level of invitations and new users. We want to ensure everyone CAN get an invitiation, but it's also nice to avoid a bot creating 2000 in one go :)
- Bonus: Before anyone is hired, Jsgenesis will operate this role through the users regular invitation balance (everyone starts with 5). These invitations can be transferred to other members, so anyone transferring them over to us, monitoring the account has "enough" and helping others transfer them will earn some goodwill!

### `HR`
1. Hire a Lead by block `#72000`
2. Set a budget for the group (for the remainder of the Term + 1 day)
3. Ensure all Workers test the onboarding process, so they know what a new user (may) have gone through.
4. Collabarate with Robert and Ben (`@cmo#1656` and `@blrhc#0162` on Discord), in designing a rough "welcome script" for anyone joinging
5. Hire Workers and start the greeting
- Bonus: Before anyone is hired, Jsgenesis will pay attention to who is greeting newcomers tomorrow when we possible get some from the Coindesk article. A helpful hand will earn some goodwill!

### `Builders`
1. Hire a Lead by block `#86400`
2. Set a budget for the group (for the remainder of the Term + 1 day)
3. Time permitting, have the Lead familiarizing themselves with the following infrastructure:
    - [Pioneer](https://github.com/Joystream/pioneer) (the new one!)
    - [Atlas](https://github.com/Joystream/pioneer)
    - [Hydra](https://github.com/Joystream/joystream/tree/master/query-node)
    - [Colossus](https://github.com/Joystream/joystream/tree/master/storage-node)
    - [Argus](https://github.com/Joystream/joystream/tree/master/distributor-node)
    - [joystream-cli](https://github.com/Joystream/joystream/tree/master/cli)
    Note that the purpose of this is mainly to ensure hiring of Workers will take our stack into account. Of course, the Builder group will also need people with other skills.

### `Marketing`
TBA

## Block Production
Although hopefully not the biggest of deals, we need some new validators for our chain. Without them, it will not be possible to recover in case the nodes Jsgenesis for bootstrapping and initial validator set crashes!

**Comment by jen4ph** [comment]
Question, can the members of the council apply for the lead positions?

**Comment by traumschule** [comment]
yes but it causes confusion :)
