### ISSUE TITLE
Forum WG Category note

### ISSUE THREAD

**Issue by bwhm** [Joystream/community-repo#737]
> Two questions ref https://github.com/Joystream/joystream/issues/3498:

> 1. What does reasonably small mean in this context? Not asking for a specific number, but orders of magnitude.
> ```
> /// Upper bounds for storage maps and double maps. Needed to prevent potential block exhaustion during deletion, etc.
> /// MaxSubcategories, and MaxCategories should be reasonably small because when the category is deleted
> /// all of it's subcategories with their threads and posts will be iterated over and deleted.
> ```

"I don't like iterations with 20-100. But it really depends on the operation. We need to benchmark troubling extrinsic first."

> 2. Does it matter at all whether we are talking "top-level" categories, or subcategories? Intuitively, I would guess:
> - Having 20 top level categories, each with 5 subcategories in each (all at the second level), is equivalent to:
> - Having 1 top level category, with 5 subcategories (all at the second level) IF you assume the same amount of threads and posts in each

" Yes. Having that we don't have forum operations with multiple categories yet."

**Comment by mochet** [comment]
> /// Upper bounds for storage maps and double maps. Needed to prevent potential block exhaustion during deletion, etc.
> /// MaxSubcategories, and MaxCategories should be reasonably small because when the category is deleted
> /// all of it's subcategories with their threads and posts will be iterated over and deleted.

WRT this, the handbook seems to state things differently: https://joystream.gitbook.io/testnet-workspace/system/forum#delete-category

### Conditions
* There are no threads in the category.
* There are no subcategories in the category.
