### ISSUE TITLE
Proposals bot 2.0

### ISSUE THREAD

**Issue by singulart** [Joystream/community-repo#765]
The DAO started to suffer from the lack of transparency. Therefore, a system of Discord notifications is required to inform respective WGs about proposals to cut/refill budgets, impose sanctions on WG Leads etc. 

Proposing to include this new proposals-related notification functionality into the [joy-disco-bots](https://github.com/singulart/joy-disco-bots/) repo. 

**Scope**
1. Send notifications to WG channels when "Set Working Group Lead Reward", "Update Working Group Budget", proposals are created
2. Other proposals lifecycle events (created, vote cast, cancelled, executed, entered grace period) should be sent to a configurable channel (#council, #proposals or any other for that matter)
3. For proposals that are about to expire (<24h), send an additional notification every hour tagging all non-voted council members ;) 
4. Notifications about comments made under proposals

**Time Budget**
1. 3h
2. 6h
3. 4h
4. 3h
Total: 16h

**Comment by freakstatic** [comment]
> For proposals that are about to expire (<24h), send an additional notification every hour tagging all council members ;)
would be better if only the ones that didn't vote were tagged

**Comment by singulart** [comment]
Point taken.

**Comment by mochet** [comment]
I think one highly important thing to possibly add should be comments made upon proposals. The older testnets didn't seem to have anywhere near as much activity when it comes to this area, so far there are already `181 posts` on proposals.

However, I am uncertain where this should actually go:
- I think including comments with the proposal announcements might create too much noise (I believe proposals and just proposals alone should have its own exclusive channel on Discord where nothing else is posted)
- or the proposal posts could be put alongside the forum-bot
- or the proposal posts could be put into the Council channel on Discord

Open for ideas, but I think given the higher level of activity with this feature it would be good to have its usage highlighted and more widely shared via Discord. I don't think it has to tag users unlike the proposal bot features, purely just announce a comment was made on a proposal.

**Comment by maxlevush** [comment]
/

**Comment by singulart** [comment]
> I think one highly important thing to possibly add should be comments made upon proposals. The older testnets didn't seem to have anywhere near as much activity when it comes to this area, so far there are already `181 posts` on proposals.
> 
> However, I am uncertain where this should actually go:
> 
> * I think including comments with the proposal announcements might create too much noise (I believe proposals and just proposals alone should have its own exclusive channel on Discord where nothing else is posted)
> * or the proposal posts could be put alongside the forum-bot
> * or the proposal posts could be put into the Council channel on Discord
> 
> Open for ideas, but I think given the higher level of activity with this feature it would be good to have its usage highlighted and more widely shared via Discord. I don't think it has to tag users unlike the proposal bot features, purely just announce a comment was made on a proposal.

updated the description with the time effort

**Comment by singulart** [comment]
@DzhideX @bwhm a kind reminder to provide Story Points

**Comment by singulart** [comment]
Proposal: https://dao.joystream.org/#/proposals/preview/374
