### ISSUE TITLE
Community Runtime Upgrade test+verification

### ISSUE THREAD

**Issue by bwhm** [Joystream/community-repo#767]
Due to the unfortunate bug with [NFTs](https://github.com/Joystream/joystream/issues/3762), we are doing a small runtime upgrade.

For the last upgrade to Rhodes, the community requested to be more involved in the upgrade. We agree with this, and will therefore have the community perform the testing of performing the upgrade itself, and verify that it works correctly afterwards.

Resources:
- [Pull request](https://github.com/Joystream/joystream/pull/3772) for the upgrade
- [Release tag](https://github.com/Joystream/joystream/releases/tag/v10.7.1) with the `.wasm` file, and how to verify the build

#### Reproduce the bug on the staging network
1. On the staging network, create an NFT owned by a channel that doesn't have a reward account set.
2. Sell it at an auction.
3. Verify the tokens are burned.

Note that it should be the case regardless of the auction type, so ideally try both types

#### Reproduce the wasm
1. Review the PR, and confirm the changes are ok (eg. nothing else than what should be adressed)
2. Perform the steps outlined in the release link, and verify the hash

#### Test the upgrade
Assuming the steps above are approved:
1. Make a proposal to upgrade the runtime, and approve it.`*`
3. Before approval or during the grace, create one of each auction type where:
   - the expected outcome is burning of the funds
   - the auction ends AFTER the upgrade has executed
4. Once the upgrade execute, complete the auction, and report back on the result. Note that I don't know what the outcome will be here, but having the funds still burned seems likely.
5. Finally, regardless of three, create one of each auction type that caused tokens to be burned, and finalize them. Verify the result is not the same

`*` Creating the proposal will likely have to be done using polkadot.js, as pioneer 2.0 injects an empty blob instead of the actual file (last time I tried).
---

## Deliverable
A document where all the steps taken are documented. 

**Auctions**
For each extrinsic/event, document:
- Blockheight
- Channel id
- NFT id
- Auction id
- Account(s) involved, and their balances before and after each extrinsic/event
- The `totalIssuance` before and after (when relevant)

A brief note of what the expected outcome was for each auction, and why.

**Runtime**
What commands was made to build, verify the hash, and make the upgrade.
Ideally, some basic functionally checks post upgrade should be made.

Story points:
10

**Comment by singulart** [comment]
Report: https://dao.joystream.org/#/forum/thread/205

**Comment by singulart** [comment]
@mnaamani Please review

**Comment by singulart** [comment]
Proposal: https://dao.joystream.org/#/proposals/preview/270
