### ISSUE TITLE
Community Runtime Upgrade

### ISSUE THREAD

**Issue by bwhm** [Joystream/community-repo#768]
As we have alluded to previously, we are considering making a change on the Council side.
It's long been a running discussion what the "right" parameters are for a Scoring Period (eg. council term length) and what the size of the Council should be.

#### Period Length
Short council terms means it's harder to make any meaningful changes over a term, especially when one considers the "lost" time between terms, due to the time from a new council is set to having it be fully operational:
- Term ends
- Grading
- New parameters and metrics
- Council and WG plans
This typically takes 3-4 days, and half the term is over.

Extending the term otoh means fewer chances to change the composition, which means fewer opportunities. 

#### Council Size
Any comparison between two possible council sizes (assuming both >1) means the larger council has a bigger freerider problem, and worse coordination and communication. This has always been a major problem, and why we reduced the number down to five. Even here, we see the problem persists.

## Scope
Make two pull requests to the Joystream repo:

1. Only reducing the size of the Council from 5 -> 3
2. In addition to the above, this also extends a term to last 14 days instead of 7 days (from 100800 blocks to 201600)

Requirements:
- The new branch should be based off [PR 3772](https://github.com/Joystream/joystream/pull/3772), and point to master once that has been merged
- No other changes that has not been discussed and approved by jsgenesis
- All tests passing, etc.

Story points:
"Only" 1  -> 10
Both 1 and 2 -> 15

**Comment by singulart** [comment]
Both PRs are ready

**Comment by mnaamani** [comment]
Looks like PR 3778 might be sufficient as it covers both council size and term changes. https://github.com/Joystream/joystream/pull/3778/commits/4cfd802a26ea79bb3ba4265608d82e0e376932cc 

But I see the council idle period was originally `57_600` and is being changed to `158_400`. This doesn't seem to match the numbers from the original scope.

**Comment by singulart** [comment]
I added whole seven days of idling. Hence the resulting figure

**Comment by bwhm** [comment]
@mnaamani @singulart 
I agree `158_400` is correct, in terms of getting a two week council, but not sure it's what we'd want!
I'd probably would prefer something like:
```
    pub const VoteStageDuration: BlockNumber = 28800;
    pub const RevealStageDuration: BlockNumber = 14400;
    pub const MinNumberOfExtraCandidates: u64 = 3;
    pub const AnnouncingPeriodDuration: BlockNumber = 57600;
    pub const IdlePeriodDuration: BlockNumber = 100800;
```

**Comment by bwhm** [comment]
I'll leave the issue open for discussion, but the task is complete per @mnaamani's comment!

**Comment by traumschule** [comment]
Are there still limitations for some proposals to execute during an election? If not we could also extend announcing vs idle to give everyone more time to prepare a candidacy:
```
    pub const VoteStageDuration: BlockNumber = 28800; // 2d
    pub const RevealStageDuration: BlockNumber = 14400; // 1d
    pub const MinNumberOfExtraCandidates: u64 = 3;
    pub const AnnouncingPeriodDuration: BlockNumber = 144000; // 10d
    pub const IdlePeriodDuration: BlockNumber = 14400; // 1d
```

**Comment by bwhm** [comment]
@traumschule 
The only "issue" AFIAK is that votes gets reset when the council changes. On runtime upgrade execution, all proposals are simply cancelled...

If we do switch the term lengths, which seems prudent, I think we should probably discuss alternatives for individual stage durations as well...

Just a signal proposal?
