### ISSUE TITLE
Idea: a simple, user-friendly UI to do QN queries

### ISSUE THREAD

**Issue by mochet** [Joystream/community-repo#769]
## Problem
On the query node (https://query.joystream.org/graphql) there is a section of it that contains templates to access information about various areas of the platform:
![image](https://user-images.githubusercontent.com/50830161/170489687-3f74cc05-63ba-41c8-a242-a5c839ec092e.png)

Here is an example of the `One Membership` query:
![image](https://user-images.githubusercontent.com/50830161/170489765-fea12515-b74c-4878-a880-408516b7152e.png)

This works really well to access data in a way that sometimes Pioneer and/or Atlas can't easily do. The only problem is that although the functionality is great, its not very user friendly for newer or less technically savvy people to use these templates. 

To illustrate how this can be offputting to users who are newer to our project:
- The `query` for `One Membership` is `1105 lines` long
- The response I included as a screenshot above is for an inactive user is `126 lines` long. I did the same query for an active user (someone who is regularly in the council) and the response came out to `5347 lines` long, These responses are quite difficult to parse even if a user has a high skill level.

## Use case
Due to the complexity of the project, there are many users who seek data for a wide variety of reasons that building into Pioneer, Atlas or the CLI would probably be extremely time consuming and expensive. The following is just a brief example of users who would benefit:
- Users who are facing difficulties with the bound staking account system
- Users who are facing difficulties with their channels
- Users who have or may not have voted on an election and want to recover stake or know something additional
- WG Leads and Workers trying to find more detailed information about their WG
- Someone wanting to find the last 50 content moderation decisions, transactions, forum posts, channels etc
- By extension of all of the above, this would also offer those helping users with difficulties in accessing pertinant information in a quicker and cleaner way.

## Idea / Solution
Build a very simple front-end where a user can select one of these queries, fill in a simple text box with what they want to query and then show the data in a simple, better laid out way than the current JSON format.
- Include the same template queries within the QN
- Have the output have all sections pre-collapsed
- Have an option to hide sections which are empty

**Comment by traumschule** [comment]
https://graphql-console.subsquid.io/?graphql_api=https://query.joystream.org/graphql
