### ISSUE TITLE
Swipe Up Videos Feature 

### ISSUE THREAD

**Issue by Delranchorecipes** [Joystream/community-repo#772]
I was thinking 🤔 one way to push Atlas to the next level would be to build up a separate app for swipe up videos, those are immensely popular right now and help keep users watching videos and spending time on the app or site. I think it’s time to start working on that or at least have it in mind because that’s where everyone is going. Soon tiktok will be bigger than YouTube and we need to stay with the trends if we want to make it mainstream. Just a thought hopefully I’m not being too radical

**Comment by traumschule** [comment]
Please reopen on joystream/atlas.
