### ISSUE TITLE
Forum bot - link is not included in the bot notification

### ISSUE THREAD

**Issue by freakstatic** [Joystream/community-repo#779]
Right now the bot doesn't include a link to easily access the post that was posted.
Example:
![image](https://user-images.githubusercontent.com/7486476/173251735-c67e7025-20a5-4287-a8ec-97f23e7d1507.png)

To improve the notification would be great to have the link to easy access the post

**Comment by singulart** [comment]
<img width="610" alt="Screenshot 2022-06-15 at 18 23 09" src="https://user-images.githubusercontent.com/7863785/173865146-f2b36160-5c39-47cc-8099-b11edef42e04.png">

**Comment by singulart** [comment]
Effort: 1h

**Comment by freakstatic** [comment]
Thanks!
