### ISSUE TITLE
Status Check - `joystream-cli`

### ISSUE THREAD

**Issue by bwhm** [Joystream/community-repo#781]
Go through all commands in the `joystream-cli`

Story points:
- including optional 10
- excluding optional 7

#### Existing Commands
If a transaction:
- Which module it belongs to
- Whether it supports all the options of said transaction
- Whether it takes inputs as `args`, `flags`, both or is "purely" interactive.
- Whether it works as intended (start a local dev-chain if difficult!)
- Whether it relies on the query-node, and if not, if it would be easier/better for a user if it did
If not a transaction:
- Which module(s) it queries
- Whether it relies on the query-node or not
- Whether it provides all the info one would expect
- Whether it, subjectively, serves a purpose or not

#### Needed Commands (transactions)
Compare the transactions supported by the cli, to all the transaction for said module.
For all transactions missing:
- Is the transaction useful, and if yes, for whom?
- Is the transaction supported by pioneer?
	- If storage or distributor related, is it supported by the storage-cli or distributor-cli?
- Would it rely on the query node?

Compare the modules with some transaction support to those without.
- Are there any transaction in said module that would be useful, and if yes, for whom?
- Is the transaction supported by pioneer?
	- If storage or distributor related, is it supported by the storage-cli or distributor-cli?
- Would it rely on the query node?

#### Deliverable
For each module with at least one transaction supported, produce a table that list all available transactions (eg. `balances.Transfer`), and if supported, the corresponding cli command (eg. `account:transferTokens`). Include the answers to the questions above in the table where applicable, and add context where needed.

For each module without any transactions supported, but you think "should be" (partially or not), list the transactions that you think should be supported, and answer the questions above.

**OPTIONAL**
#### Needed Commands (non-transactions)
Finally, are there any non-transaction commands that would be useful for some working group or users, that the cli doesn't support, and isn't available elsewhere.
Ask the Leads for each group, and potentially some users that have a particular interest in one module, and:
- Outline roughly what you/they would want, and how to get there.

#### Optional Deliverable
List the "wanted" non-transaction commands, and answer the question above.

**Comment by traumschule** [comment]
created a structure:
https://github.com/traumschule/joystream/blob/cli-commands/cli/doc/Commands.md
To add info just create a PR to the branch and i'll merge it!

@singulart i suggest to assign a worker to help fill the tables and communicate to leads, not sure when i get to it.
