### ISSUE TITLE
FM Program: Agree on viable improvements for grading process/post-mainnet

### ISSUE THREAD

**Issue by mochet** [Joystream/community-repo#793]
- [ ] Discuss/decide on if there are any viable improvements that are low resource and quick delivery for the FM grading process
- [ ] Consider the likely impact of changing tooling from current choices and regularity of delivery
- [ ] Try to think/predict how mainnet governance will happen

**Comment by singulart** [comment]
@mochet You mentioned that FM program won't exist post-mainnet.
