### ISSUE TITLE
Query Node timestamps

### ISSUE THREAD

**Issue by bwhm** [Joystream/community-repo#797]
"Story Points:" 15

### Timestamps
Each query has a couple of fields where the type is a timestamp, eg. `createdAt`, `updatedAt`.

At least for the bounties, it is the case that these are updated with `new Date()` as the "standard" 
`new Date(event.blockTimestamp)` isn't available, simply because there is no event associated with certain stage changes here.

This makes it so that two instances of the query node will never show the exact same data.

### Bounty Stage 
The bounties have also provided incorrect data about the stages at certain points. This may be a consequence of this, that the handler may not be getting some data asynchronously, both or something else.

### Timestamps
Find all instances affected by this issue, and make a PR with (a) proposed fix(es). Note that the `blockTimestamp` is available for all blocks, so the handler should be able to use the "correct" timestamp.

### Bounty Stage
Review the handler, and find the actual cause of the issue. No PR is needed, but an extra 5 points if a fix gets merged.

**Comment by singulart** [comment]
Proposal: https://dao.joystream.org/#/proposals/preview/323

**Comment by freakstatic** [comment]
I found what at least this fields have different timestamps for different QN instances:
Fields with different timestamps:

    bounties
        createdAt
        updatedAt
    [Diff](https://www.diffchecker.com/dnisVyY7) 

```
    query {
        bounties (orderBy:title_ASC, limit:1000) {
            id,
            createdAt,
            updatedAt
        }
    }
```


    workingGroupOpenings
        createdAt
   [Diff]( https://www.diffchecker.com/2cugioLM
)
```
    query {
        workingGroupOpenings (orderBy: runtimeId_ASC, limit: 1000) {
        id,
        createdAt
        updatedAt
        }
    }  
```  


    channelNftCollectors
        createdAt
        updatedAt
        lastIncreaseAt
    [Diff](https://www.diffchecker.com/VgUUoEEz
)
```
    query {
        channelNftCollectors (limit: 1000) {
            id,
            createdAt,
            updatedAt,
            lastIncreaseAt
        }
    }
```
    

    workingGroups
        createdAt
        updatedAt
    [Diff](`https://www.diffchecker.com/VmgxxkFs`)

```
    query {
        workingGroups (limit: 1000) {
            id,
            createdAt,
            updatedAt
        }
    }
```


    workers
        createdAt
        updatedAt
   [Diff]( https://www.diffchecker.com/SxuhdFx7)

    ```
query {
        workers {
            id,
            createdAt,
            updatedAt
        }
    }
```

**Comment by freakstatic** [comment]
For the bounties I found the following places where `new Date()` is used
https://github.com/Joystream/joystream/blob/3153a3f7f4cef19f2441e92c6de57e7b897e84a6/query-node/mappings/src/bounty.ts#L215

https://github.com/Joystream/joystream/blob/3153a3f7f4cef19f2441e92c6de57e7b897e84a6/query-node/mappings/src/bounty.ts#L197

https://github.com/Joystream/joystream/blob/3153a3f7f4cef19f2441e92c6de57e7b897e84a6/query-node/mappings/src/scheduler.ts#L62
