### ISSUE TITLE
Displaying bytes served in Argus logs

### ISSUE THREAD

**Issue by alexznet** [Joystream/community-repo#805]
This ticket is inspired by following Discord post:
https://discord.com/channels/811216481340751934/933726271832227911/985936622627454988

In a nutshell - sample log record is shared in the Discord message above. Right now there is no information in Argus logs (even in 'debug' level) about bytes served by request.  That information can be helpful for log analyzing and measuring. For example, measuring total bytes served per node & collecting statistics.

Please share your opinions and if this looks useful - it would be great if that could be implemented. That would allow to have some additional ability for nodes monitoring/measuring performance.

**Comment by traumschule** [comment]
Please reopen on joystream/joystream.
