### ISSUE TITLE
Community Bounty #7 - "Joystream Player Loading"

### ISSUE THREAD

**Issue by bwhm** [Joystream/community-repo#85]
### Tags
- `Research`
- `Coding`

## Description
The current implementation of the [Joystream Player](https://github.com/Joystream/atlas) hosted [here](play.joystream.org) takes a while to load. There are some known reasons for this, but there may also be some unknown sources. While all of the items listed below will contribute, note that the first one is the main point of interest in this bounty
- Javascript processing while loading the app
- Loading static assets
- Querying [Hydra](https://hydra.joystream.org/graphql), to get the videos and channels. See [github](https://github.com/Joystream/hydra)
- Fetching the metadata assets for videos and channels, from various URLs.
- Querying [Orion](https://orion.joystream.org/graphql), to get view counts. See [github](https://github.com/Joystream/orion)

### Reward
Up to USD 400, depending on the quality of the work.

### Format
Jsgenesis requests a [closed](https://github.com/Joystream/helpdesk/tree/master/roles/builders#closed) format.

### Success Events
1. Benchmark the individual sources of loading time, and compare across browsers - $150.

The deliverable is a report that breaks down the individual sources of loading time, and quantifies them.
The following browsers must be included in the tests:
- Chrome
- Firefox
- Brave
In addition to opening the landing page, loading times for both browsing and directly accessing a specific video and channel must be included.
If possible, test on different hardware, and include the specs, OS and versions of browser/OS.

2. Provide solutions that would decrease the loading times - $250.

The deliverable is a report looking into the non-trivial sources of load time, and produce high-level ways of reducing them. Although querying Hydra and Orion will play a role, this is outside the scope of this bounty. The main focus is to try to optimize the JS app itself.

Note that if you think you are able to improve the code yourself, reach out to us. If so, a new success event, with better rewards, will be added.

### Conditions
- The reports are submitted as a PR to the [Community Repo](https://github.com/Joystream/community-repo/)
- The reports are licensed as GPLv3, in accordance with the repo.

### Annihilation
NA

### Review Period
Once the Council approves the PR, by requesting reviews from @bwhm and @blrhc , Jsgenesis will grade and potentially increase the fiat pool, within 1 week.

### Status
[See forum post](https://testnet.joystream.org/#/forum/threads/214)

**Comment by bwhm** [comment]
@mochet 
If this has not been assigned (it looks like it hasn't), I am going to close this as the Atlas team solved it themselves :)

**Comment by mochet** [comment]
> @mochet
> If this has not been assigned (it looks like it hasn't), I am going to close this as the Atlas team solved it themselves :)

This was never assigned and no one expressed interest in it, so I would say its safe to close

**Comment by mochet** [comment]
I will mark this in the JSON as "withdrawn - no interest"
