### ISSUE TITLE
Community Bounty #8 - "Ledger for Joystream"

### ISSUE THREAD

**Issue by bwhm** [Joystream/community-repo#86]
### Tags
- `Research`

## Description
Research how well the Ledger hardware wallet is supported, how to use them on the network, derivation paths and key recovery.

### Reward
USD 450

### Format
Jsgenesis requests a [closed](https://github.com/Joystream/helpdesk/tree/master/roles/builders#closed) format.

### Resources
You must have/buy a Ledger[*](#notes) hardware wallet, and connect pioneer to a node you control, running with flags: `--log runtime,txpool,transaction-pool` to work on this bounty. If you are not already running a node, setting up a [devchain](https://github.com/Joystream/joystream/tree/master/node) might be useful...
- [Pioneer](https://testnet.joystream.org/#/accounts)
- [Polkadot JS apps](https://polkadot.js.org/apps/#/accounts)
- [Polkadot JS extension](https://polkadot.js.org/extension/)
- [Ledger Support](https://support.ledger.com/hc/en-us/articles/360016289919-Polkadot-DOT-)
- [subkey](https://substrate.dev/docs/en/knowledgebase/integrate/subkey)
- [Ian Coleman's BIP39 tool](https://iancoleman.io/bip39/)

##### Notes
- It is not clear if both Ledger Nano X and Ledger Nano S is compatible with the polkadot app.
- For all of the tests below, please use a fresh device, or verify your existing backup is safe and can be recovered, then wipe your device and generate a **new seed** on your device to avoid compromising your seed and funds in any way.
- To complete all the steps, you must expose your seed in order for anyone to verify the information provided.
- Jsgenesis can not be held responsible for any loss of funds as a result of performing this bounty.
- Make sure you use the most recent firmware and application version on your ledger device.

### Success Events
The final deliverable is a report answering all the question below, in a way such that the reader of the report can understand the findings without having to read anything else than the report. Simply answering "yes" or "no" is not sufficient, and steps to reproduce, sources etc. must be provided.

The workload and reward for the success events assumes that only one keytype is supported, and the Polkadot JS extension is required to use alongside Pioneer. If this turns out to be incorrect (eg. more keytypes, and you can use Pioneer without the extension as well), the reward for success event 3 will be increased. If it turns out you can't use a Ledger on Joystream at all, only success events 1,2 and 5 applies.

1. Test compatibility of Ledger on Joystream - USD 50
  - Can a Ledger be used to sign transactions on [Pioneer](https://testnet.joystream.org/#/accounts) w/o an extension?
    - If no: Can a Ledger be used to sign transactions on [Polkadot JS apps](https://polkadot.js.org/apps/#/accounts) w/o an extension?
  - Can a Ledger be used to sign transactions on Pioneer with the [extension](https://polkadot.js.org/extension/)
    - If no: Can a Ledger be used to sign transactions on Polkadot with the [extension](https://polkadot.js.org/extension/)

2. Which substrate keytypes are supported by Ledger - USD 50
  - Schnorrkel (`sr25519`)?
  - Edwards (`ed25519`)?
  - `ECDSA`?

3. Transaction testing - USD 100
  - Test (at least) a single transaction from each `section`, and log:
    - `method`
    - `input`
    - data displayed on ledger (can be image)
    - data displayed in Pioneer/extension (can be screenshot)
    - if fail:
      - error message(s) displayed Pioneer/extension (can be screenshot)
      - error message displayed on node (if any)

4. What are the derivation paths, and recovery mechanism, for each keytype supported - USD 200
  - Find the derivation path used for each of the keytypes supported.
  - Check if you are able to successfully recover the key without using a Ledger, and sign a transaction with it, by some mix of:
    - the BIP39 tool
    - Subkey
    - Pioneer
    - Polkadot/substrate documentation
  - If successful: note down all steps, and results in such a way that your results are reproducible
    - Your seed
    - All commands
    - All results
    - Everything you inserted in to the browser
  - If unsuccessful: note down all steps of your attempts, and results in such a way that your results are reproducible, and/or can be ruled out by someone else attempting this

5. Research, without any testing required, if any other hardware wallet manufactorer supports Polkadot/substrate (and by extension Joystream) - USD 50

### Conditions
- The reports are submitted as a PR to the [Community Repo](https://github.com/Joystream/community-repo/)
- The reports are licensed as GPLv3, in accordance with the repo.
- 
### Annihilation
The report contains anything that tries to lure users to expose their seeds.

### Review Period
Once the Council submits the report from success event 1, and @bwhm and @blrhc is assigned to review, Jsgenesis will grade within 1 week.

### Status
[See forum post](https://testnet.joystream.org/#/forum/threads/215)
Closed with #171 

$450 fiat pool increase!

**Comment by mochet** [comment]
This has been assigned and delivered, it is pending grading: https://testnet.joystream.org/#/proposals/56
