### ISSUE TITLE
Livestreaming toolkit

### ISSUE THREAD

**Issue by mochet** [Joystream/community-repo#864]
Livestreaming is not a part of Joystream and it isn't clear this will ever happen in the near term, however, there are enough publicly available tools that can be utilized to make Joystream a viable platform for livestreaming.

It should be noted that it appears that certain livestreamers enjoy large audiences which have been quite important to the success of some platforms.

This would include:
- The actual livestreaming functionality + whatever backend is necessary (servers, CDN etc)
- Perhaps some functionality to automatically upload finished livestreams to Joystream as media files
- Perhaps using placeholder Joystream uploads (i.e. an upload with metadata but not media file) that can be used for the livestreaming event (thus making the livestream be "somewhat on-chain")
- Tooling to allow the use of $JOY or $CRTs for tipping creators and incorporating this in popular livestreaming software such as OBS

**Comment by traumschule** [comment]
This can be part of third-party apps but considering costs on scale this is unlikely to become integral part anytime soon.

**Comment by mochet** [comment]
Todo:

- [ ] Identify and categorize available tooling/websites
- [ ] Figure out how complex it is to implement the livestreaming UI (video feed + chat) into Atlas or whether it is maybe an option to just do an external link/pop out window with a preexisting design/tool
- [ ] Figure out how expensive it is to do tipping functionality using on-chain transactions
- [ ] Figure out how viable it is to create "blank" videos on Joystream that can be appended with a future time/date for a livestream and then have a video uploaded once the livestreaming is over
- [ ] Try to get some idea of what the costs would be for infrastructure (CDN, server to upload completed livestreams etc)
