### ISSUE TITLE
Community Bounty #10 - "Upload Public Domain Content"

### ISSUE THREAD

**Issue by bwhm** [Joystream/community-repo#88]
### Tags
- `Content`

## Description
As part of the [Babylon release](), the new consumer application was launched. To showcase it, Jsgenesis uploaded some 300 videos of [Public Domain](https://creativecommons.org/share-your-work/public-domain/pdm), and other [Creative Commons](https://creativecommons.org/licenses/) permissively licensed content.

We believe there are some hidden gems available out there, that is licensed permissive.

### Reward
Up to USD 5 per video.
**Update - 09.07.21**
Effective from block `#1386000`, there will be a cap of $500 paid out per week. 
The BM/Council are free to design the distribution scheme.

### Format
This will be an "open" bounty, where all users can contribute without the need to be assigned. Users are encouraged to submit their videos in batches to avoid cluttering the proposal system. Duplicate entries will be graded by time of upload, not time of submissions.

Steps for participants:
- Upload one or more video to the platform.
- Provide links in the (tbd) forum post for the Curators and the Admins (tbd) to review.
- After the videos are approved by the Curators, the Admins will grade them and set a total reward.
- Create a spending proposal based on the then prevailing exchange rate listing the `entityId`, and title of all your videos, along with a link to the forum post where the Admin grades them.
- Unless the Council can raise legitimate concerns, they will approve.

Workload for the Council:
- Assign one or more Admin to grade the videos, and agree on a reasonable weekly compensation. This will be reimbursed by Jsgenesis.
- Once a week, the Council (Secretary) produces a report that lists all the submissions and:
  - The `memberId` of all participants, and a link to the associated spending proposal.
  - For each of these the `entityIds`, titles and reward for each entry.
- The report is delivered as a PR to the [Community Repo](https://github.com/Joystream/community-repo/).

### Success Events
1. Source interesting videos online, and upload them to appropriate channels.
Videos are graded on:
- quality of video/audio
- quality of metadata for the video:
  - thumbnail
  - descriptions
  - release year
  - etc.
- quality of metadata for the channel:
  - cover
  - avatar
  - title
- length of content
- quality of content
- relevance to the platform
  - a video discussing eg. cryptocurrency or governance is more "relevant" than a pre-game show of a sporting event that occurred 70 years ago.

### Conditions
- All media files and metadata files/links must be in the public domain, or other permissive license
- All metadata is set correctly, especially if relevant to the license (eg. attribution if required)
- Duplicates will not be accepted unless the quality is significantly better
- Videos are placed in channels themed appropriately (eg. a cryptocurrency video shouldn't be in a baking channel)

### Annihilation
- Anything that violates the platforms ToS and/or any license or copyright.

### Review Period
- Jsgenesis will perform bulk reviews, every Tuesday.

### Status
[See forum post](https://testnet.joystream.org/#/forum/threads/217)

**Comment by mochet** [comment]
This bounty now has a manager (stwoof). If you are interested in submitting your videos for rewards, please submit them on the forums via this link: https://testnet.joystream.org/#/forum/threads/292

**Comment by bwhm** [comment]
We are closing this now. More targeted content bounties should (finally) open soon(tm).
