### ISSUE TITLE
Community Bounty #11 - "Design Community Repo Banner"

### ISSUE THREAD

**Issue by bwhm** [Joystream/community-repo#89]
### Tags
- `Design`

## Description
Most of the repos in the Joystream organization have branded banners in their README.md.

These were made a while back, when the project was in a different place, so some are now missing. We are in the process of making new ones for these, but for the [Community Repo](https://github.com/Joystream/community-repo/), we want the community to design one.

Examples of current ones in the [Helpdesk](https://github.com/Joystream/helpdesk):
https://github.com/Joystream/helpdesk/blob/master/roles/builders/img/builder_new.svg
https://github.com/Joystream/helpdesk/blob/master/img/helpdesk_new.svg
https://github.com/Joystream/helpdesk/blob/master/roles/img/roles_new.svg
https://github.com/Joystream/helpdesk/blob/master/roles/content-curators/img/content-curators.svg

### Reward
USD 250.
USD 100 will be awarded to the entry that the Council approves, whereas an extra USD 150 will be awarded if it passes (potentially after some feedback) the critical eye of @bedeho.

### Format
Jsgenesis proposes a ["free for all"](https://github.com/Joystream/helpdesk/tree/master/roles/builders#free-for-all) format.

### Success Events
1. Design a banner for the Community - USD 100.
The Council will be allowed to approve up to three candidates, each awarded USD 100.

2. *If* one (or more) of the designs are approved by @bedeho, each of them will be awarded an extra USD 150.

### Conditions
- The banner must be delivered in both .svg and .png format, in the same dimension as the existing ones.
- The banner must be licensed as GPLv3
- The banner is submitted as a PR to the [Community Repo](https://github.com/Joystream/community-repo/)
- The font and background could be the same, but doesn't strictly have to be. See [Design Repo](https://github.com/Joystream/design).

### Annihilation
- The banner violates any copyright or license.

### Review Period
- Up to 1 week, including feedback and iterations.

### Status
[See forum post](https://testnet.joystream.org/#/forum/threads/218)

**Comment by botzmann** [comment]
Banner
https://d.radikal.ru/d19/2102/12/b80451cd8d59.png
botzmann 5EA1RhYg4NCJp4qfvTYNzVCSGF5X7VF2VeKFm21kTbqfoZxe

**Comment by mochet** [comment]
This bounty has concluded, the results were posted here: https://testnet.joystream.org/#/forum/threads/344
All rewards have been paid out
